### ISSUE TITLE
Deno 1.7.0 error

### ISSUE THREAD

**Issue by allangomessl** [alephjs/aleph.js#101]
When we create a project on 1.6.3 works, but 1.7.0 cause these errors

How to reproduce:

╰─❯ aleph init hello
╰─❯ cd hello
╰─❯ aleph dev                                                                                                                                                                      
Check https://deno.land/x/aleph/cli.ts
error: Uncaught (in promise) NotSupportedError: Cannot set "location".
        throw new DOMException(`Cannot set "location".`, "NotSupportedError");

**Comment by shadowtime2000** [comment]
This was a previous issue, this has already been fixed and in the next release it will be patched. We haven't released it yet because there are a couple other bugs that need fixing.

**Comment by ije** [comment]
let's keep it open until next patch date!

**Comment by VaibhavAcharya** [comment]
Hey! New to Deno here, What can I do in the meantime?

**Comment by FallingSnow** [comment]
@ije can we release v0.2.29 with just this patch?

**Comment by ije** [comment]
please use deno 1.6.3  indeed, i will release a beta version ASAP this week!

**Comment by FallingSnow** [comment]
If anyone needs to install deno 1.6.3 easily, please checkout https://github.com/justjavac/dvm.

**Comment by ije** [comment]
i just released an _alpha_ version, now it should work in deno **1.7**.

**Comment by ije** [comment]
please update the cli command:

```bash
deno install -A -f -n aleph https://deno.land/x/aleph@v0.3.0-alpha.1/cli.ts
`

**Comment by FallingSnow** [comment]
0.3.0 fixes the `--location` error.

**Comment by jeffrey-l-turner** [comment]
I'm still getting the same problems on Mac with Deno 1.7.3

**Comment by shadowtime2000** [comment]
@jeffrey-l-turner As in the same error? Have you upgraded to the latest version of Aleph?

**Comment by hagenek** [comment]
Hi. Getting the same error on Deno 1.10.2.
