### ISSUE TITLE
Custom Document support.

### ISSUE THREAD

**Issue by forgo** [alephjs/aleph.js#102]
Everything in the custom `app.tsx` currently gets placed into an html `<main>` tag.

If I want to create a document template with a `<nav>` component, that contains page `<Links>`, it is not semantically correct for this to be inside the `<main>` unless it is a table of contents or tab navigation within the page itself.

I believe this [Custom Document](https://nextjs.org/docs/advanced-features/custom-document) feature of Next.js was made for this purpose, but I don't see a way to currently do this in Aleph.

If that's not planned, would it be simple enough to change the following lines to use something like `<div id="aleph-app">` instead of `<main>` to give flexibility to the user to adhere to their own semantic [nav](https://www.w3.org/TR/html51/single-page.html#elementdef-nav) and [main](https://www.w3.org/TR/html51/single-page.html#the-main-element)?

https://github.com/alephjs/aleph.js/blob/659337e33846250e1f0e8e6c4977838caff0e549/server/project.ts#L232

https://github.com/alephjs/aleph.js/blob/659337e33846250e1f0e8e6c4977838caff0e549/framework/react/bootstrap.ts#L60

Thank you for the consideration and work on this project.

**Comment by ije** [comment]
@forgo, thanks for the suggestion, i prefer `<div id="__aleph">` instead of `<main>`.

**Comment by shadowtime2000** [comment]
I would like to point it that document is meant for stuff like google analytics and third party scripts, not stuff like actual components. I think it would be semantically correct for it to be inside a `<div id="__aleph">` which is kind of like what NextJS does.

**Comment by shadowtime2000** [comment]
Document support would be pretty nice tho it may not be used much because of the built in features of `<script>` tags and such - so I think this is something we can implement later
