### ISSUE TITLE
Non english urls support

### ISSUE THREAD

**Issue by ZiiMakc** [alephjs/aleph.js#105]
Is it possible for aleph to accept non english urls like "тест" (%D1%82%D0%B5%D1%81%D1%82)?

In next.js you can do it in config with [rewrites](https://nextjs.org/docs/api-reference/next.config.js/rewrites):
```
module.exports = {
  async rewrites() {
    return [
      {
        source: encodeURI('/тест'),
        destination: '/test',
      },
    ]
  },
}
```

**Comment by ije** [comment]
@ZiiMakc thanks, this is in the plan of **v0.3**

**Comment by shadowtime2000** [comment]
Rewrites would also be a nice feature.
