### ISSUE TITLE
Import a script inside a component or api cause an error

### ISSUE THREAD

**Issue by RoXuS** [alephjs/aleph.js#107]
Hey!

I'm trying to call a script outside my aleph project (I am on a monorepo project).
```ts
import React from "https://esm.sh/react";
import a from "../../dt-gitlab-wrapper/index.ts";

const b = new a("1");

export default function Runners() {
...
}
```

When I do that I get the following error:
![image](https://user-images.githubusercontent.com/3296671/106210057-68868f80-61c6-11eb-90a3-2d78e64a6608.png)

It's normal behavior? We can't call a script outside the component?

**Comment by shadowtime2000** [comment]
I would call this normal behavior because you should only be importing stuff from CDNs and from within the project folder. It does make the situation a little ugly for monorepos though, monorepos with deno is something that is still being figured out though anyways.

**Comment by Soremwar** [comment]
You only use "../" or "./" relative paths when the file exists locally in your machine. If it doesn't then you should be using an URL to import from wherever you have it

**Comment by RoXuS** [comment]
hum my other projects inside the monorepo work well (install, bundle...).
I don't understand why a TS file inside my project works and just above is KO?

**Comment by FallingSnow** [comment]
This might be due to the fact that alephjs movies files around before executing them. I know this isn't an import but this is how I access files.
```ts
import * as path from "https://deno.land/std@0.83.0/path/mod.ts";

const dir = path.fromFileUrl(import.meta.url);
const projectDir = path.resolve(dir, "../../../../"); // The files are located in the same directory (api), but in order to work, you need to move up 4 directories for the project root directory.
const schemaFilePath = path.resolve(projectDir, "api/schema.gql");

Deno.readTextFileSync(schemaFilePath);
```

**Comment by Soremwar** [comment]
@RoXuS Can you please show your project structure? I feel like I am giving advise without actually knowing what I'm dealing with

**Comment by RoXuS** [comment]
@Soremwar off course.

My structure:
![image](https://user-images.githubusercontent.com/3296671/106324972-5b2add00-627a-11eb-8b77-7d5cffd57c47.png)

My `components/runners.tsx` try to access to `dt-gitlab-wrapper/index.ts` and it doesn't work (with a symlink it is ok).

@FallingSnow it seems hard to do that with a file import like `import a from "../../dt-gitlab-wrapper/index.ts";` no?

**Comment by FallingSnow** [comment]
Yeah. I don't know if deno supports `require`, I've never tried but that could be a possible solution.

**Comment by ije** [comment]
i seems the `git-wrapper` is out of your aleph app scope that alephjs can't handle it, I will fix this, thanks!

**Comment by ije** [comment]
please use synlimk as workaround currently

**Comment by RoXuS** [comment]
works as expected on 1.8.0, THX!
