### ISSUE TITLE
Top-level await is not removed

### ISSUE THREAD

**Issue by hazae41** [alephjs/aleph.js#108]
Hey, when importing a deno std module that uses top-level await, I receive an error

```typescript
import { createHash } from "https://deno.land/std@0.85.0/hash/mod.ts";
```

![Capture](https://user-images.githubusercontent.com/4405263/106313118-f9617780-6267-11eb-933c-66255c5f8006.PNG)

![Capture](https://user-images.githubusercontent.com/4405263/106313229-29a91600-6268-11eb-8632-7fe5aea3aea8.PNG)

The source file: https://deno.land/std@0.85.0/hash/_wasm/hash.ts

**Comment by shadowtime2000** [comment]
Thanks for reporting this bug, I think we could solve this with the new compiler.

**Comment by ije** [comment]
in production/bundle mode this can be fixed, but in dev we can't resolve it needs the browser support...

**Comment by hazae41** [comment]
> in production/bundle mode this can be fixed, but in dev we can't resolve it needs the browser support...

Maybe we could have a mode that behaves like "dev" but is widely compatible like "production"?

**Comment by ije** [comment]
chrome 89+ will support it:
![image](https://user-images.githubusercontent.com/2883484/107150632-b0ad6b00-6999-11eb-9162-050ede9b2f4f.png)

**Comment by ije** [comment]
we are using es module in dev mode that is vary simple and good for compilation, it is bad to bundle code in dev.

**Comment by FallingSnow** [comment]
Chrome 89 has been release. Can we close?

**Comment by shadowtime2000** [comment]
Yeah, this isn't something we can necessarily fix and browsers are starting to support it like Chrome 89.
