### ISSUE TITLE
aleph dev startup fail on windows

### ISSUE THREAD

**Issue by hokkqi** [alephjs/aleph.js#116]
Hello, on the latest version of Aleph, after running `aleph init`, i.e. when I then want to run `aleph dev` I get uncaught DomException Error telling me that Aleph is unable to set the `location`.

**Comment by ije** [comment]
@hokkqi please update the `aleph` command to **v0.3.0-alpha.1** that can work in deno 1.7

**Comment by ije** [comment]
please check #101

**Comment by hokkqi** [comment]
While it did start up, I got [this Error Log](https://h.scy.re/gucuhavanu.js) in my Terminal when running `aleph dev` on my other Computer, I'll test if it's working on the one that initially made it error out

**Comment by ije** [comment]
thanks, this typing error you can ignore since it will not effect the aleph server, but i alreay fixed.

**Comment by hokkqi** [comment]
2 more things:

- the Hello World counters don't seem to work
- Aleph is unable to build/output the Bundle `Unable to Bundle during Graph::bundle().`

**Comment by ije** [comment]
- hello world's counter i don't know what happened, any output in the console?
- in v0.3 i am trying to share cache with Deno built-in cache system, that makes `Graph::bundle` error happen when the network is not stable, i will improve this.

**Comment by hokkqi** [comment]
- There's no output in the console, not sure why
- good to know! 😄

**Comment by ije** [comment]
@hokkqi thanks, what deno version you are using btw.

**Comment by hokkqi** [comment]
1.7.0

**Comment by ije** [comment]
thanks, 1.7.0' bundler has an issue for alephjs, pls upgrade 1.7.1

**Comment by hokkqi** [comment]
Still getting the same error when trying to run `aleph start` but that's fine for me rn, I just need the dev environment

**Comment by swork1** [comment]
> Still getting the same error when trying to run `aleph start` but that's fine for me rn, I just need the dev environment

I am also getting the same problems. 
1. **"aleph dev'** doesn't load bundled js -> error in console is **"Not allowed to load local resource"**
2. "aleph start/build" gives me Graph::bundle error -> I see you are fixing this

**Comment by ije** [comment]
@swork1 thanks, aleph dev mode doesn't bundle the code, only bundle in `start/build`, where the error printed actually? browser or deno?

**Comment by ije** [comment]
and i never test it in the windows port.

**Comment by swork1** [comment]
> @swork1 thanks, aleph dev mode doesn't bundle the code, only bundle in `start/build`, where the error printed actually? browser or deno?

This is a console error in the browser. (I'm also using windows which could be the issue?)

**Comment by ije** [comment]
@swork1 thanks, not sure i will test on it, now the CI on windows is passed.

**Comment by shadowtime2000** [comment]
Seems like this is happening where the browser starts loading bundled files from `file:///` instead of loading unbundled files from the dev server. Possibly a problem with the cache...

**Comment by shadowtime2000** [comment]
I looked into it more and seems like it is because of a usage of `std/path` on the links to preload and stuff when we shouldn't be doing that

**Comment by shadowtime2000** [comment]
I think figured out where part of the problem is coming from. A couple places in `app.ts` we are appending `file://` at the start of the names of modules which is causing the browser to look in `C:\` or something where it won't be able to find anything because it's not there. It should be using the whole path so that the browser knows where to look, but @ije why aren't we instead importing straight from the dev server? I think pointing browsers to look through the file system is a privacy thing that many people don't want to risk.

**Comment by ije** [comment]
so it is an issue in windows? can you please post the html by SSR?

**Comment by shadowtime2000** [comment]
@ije This is from @swork1 on the discord and I can confirm it is the same

![image](https://user-images.githubusercontent.com/66655515/106692852-22487c00-658a-11eb-835c-09795b5ee49b.png)

**Comment by shadowtime2000** [comment]
something in `app.ts` is converting the `/` absolutish imports into file paths which causes the browser to default to `file://`, or on windows somehow we are preppending `file://` to the module names

**Comment by ije** [comment]
thanks @shadowtime2000

**Comment by ije** [comment]
**@v0.3.0-alpha.2** is working on windows now.
