### ISSUE TITLE
Change srcDir or provide alternative

### ISSUE THREAD

**Issue by jackleslie** [alephjs/aleph.js#12]
# Issue

Really excited about this project, it looks so cool - already starting to use it for a personal project to try it out!

I was wondering about the use of `/` as the default `srcDir` - in Next.js you are able to use both `/` and `/src`, even with `pages`:

https://nextjs.org/docs/advanced-features/src-directory

The benefits of using `src`, in my experience, is noticeable when projects start to scale and use more and more tools that require configuration files (e.g `.eslintrc`, `.babelrc`, `tsconfig.js`, npm/yarn files etc). When this starts to happen, the top-level of projects can get cluttered with lots of files, and it's nice to be able to separate config files from source code.

A quick example: https://github.com/vercel/swr, lots of config files but all source code in `/src`

# Solutions

If this is an issue that you agree with and would like to tackle then there are a couple of initial solutions:

### Easy solution

**Changing the `srcDir` completely from `/` to `src`**
- Good: one-liner code change:
> https://github.com/alephjs/aleph.js/blob/6940dcffb39796a7b945de2bd2aa0eaf5d634ca1/project.ts#L79
> Change to `srcDir: '/src', `
- Bad: forces everyone to have to use `/src`, including `/src/pages` which is commonly top-level in Next.js projects

### Slightly-less-easy solution

**Offer a choice between `/` and `/src`**
- Good: another one-liner code change
> https://github.com/alephjs/aleph.js/blob/6940dcffb39796a7b945de2bd2aa0eaf5d634ca1/project.ts#L79
> Change to `srcDir: existsDirSync('/src') ? '/src' : '/',`
- Good: means people can choose and aren't forced into using `/src`, which can be a preference for small projects
- Bad: Unless you do some more changes to the code, there's no hybrid option with this (e.g if someone wants to use `/pages` at top-level but wants all other source code in `/src`, as is common in Next.js projects

### Other

Not familiar with the codebase but I'm sure there would be a solution to offer the hybrid approach if that is preferred.

# Conclusion

Quite a big description for such a small change, but let me know what your thoughts are!

**Comment by shadowtime2000** [comment]
I think this is a good idea.

**Comment by ije** [comment]
make a lot of sense, or handle this within `aleph init` command, a simple *UI* to initiated some basic options like `srcDir`

**Comment by ije** [comment]
hi @jackleslie can you make a pull request? i think `srcDir: existsDirSync('/src/pages') ? '/src' : '/'` is good, more friendly, then let's improve the `init` command!
thanks.

**Comment by jackleslie** [comment]
Sure @ije! Would you like me to add some tests? Or perhaps edit one of/all of the examples so that they use `src`?

**Comment by ije** [comment]
the `srcDir` should work i already tested before, i will add an example later. thanks!

**Comment by ije** [comment]
done, thanks @jackleslie
