### ISSUE TITLE
HMR not working with Windows 10 WSL (Windows Linux Subsystem)

### ISSUE THREAD

**Issue by borsemayur2** [alephjs/aleph.js#120]
I've installed deno and aleph on ubuntu OS (using Windows 10 WSL). HMR is not working for some reason.

**Comment by shadowtime2000** [comment]
@borsemayur2 Please provide more details such as Aleph version and Deno version.

**Comment by borsemayur2** [comment]
Versions:
1. Deno: 1.7.1
2. Aleph: v0.3.0-alpha.4

HMR works with Windows 10 install but not with WSL

**Comment by FallingSnow** [comment]
Hmmm, strange. Maybe something having to do with listening for file changes on WSL.

**Comment by shadowtime2000** [comment]
@borsemayur2 Are there any errors in the browser console?

**Comment by borsemayur2** [comment]
No. Console says "[HMR] listening for file changes..."

**Comment by ije** [comment]
not sure whether is deno fs watch api problem in WSL, will test on it. @shadowtime2000 can you please look into it?

**Comment by ije** [comment]
@borsemayur2 thanks for the details, will fix it ASAP

**Comment by borsemayur2** [comment]
Okay. Let me know if I can help in fixing this issue.

**Comment by shadowtime2000** [comment]
> not sure whether is deno fs watch api problem in WSL, will test on it. @shadowtime2000 can you please look into it?

I don't use WSL (I embrace the full power of the cmd :p) but I will try to set it up to reproduce asap.

**Comment by Hunam6** [comment]
Don't worry @shadowtime2000, it's pretty simple to install, even with the manual way.

**Comment by borsemayur2** [comment]
Updates: The issue is with WSL and not Aleph. File changes for `/mnt` (windows FS for instead of Linux) not supported. The app needs to be setup in Linux path. [HMR not working on WSL 2](https://github.com/microsoft/WSL/issues/4417)

Thus, we closing this issue.

**Comment by moracabanas** [comment]
Sorry about to reopen this thread, but i'm trying Parcel with Linux FS instead windows /mnt and still not working.
