### ISSUE TITLE
baseUrl doesn't work

### ISSUE THREAD

**Issue by oyzhen** [alephjs/aleph.js#121]
aleph version: 0.3.0-alpha.4

Initialized project by `aleph init` and configured `aleph.config.ts`:

```TypeScript
export default {
    baseUrl: '/123/'
};
```

However, all the static files under baseUrl cannot reach
![image](https://user-images.githubusercontent.com/52534412/106996544-2b209400-67bc-11eb-9f44-45efc0ab6a26.png)
![image](https://user-images.githubusercontent.com/52534412/106996561-35429280-67bc-11eb-9eca-5f079f4210a7.png)

May be you need to trim the baseUrl on the `aleph/server/server.ts` 
![image](https://user-images.githubusercontent.com/52534412/106996812-a1bd9180-67bc-11eb-8ea1-4eb2f7898643.png)

**Comment by shadowtime2000** [comment]
@oyzhen Thanks for reporting this, it would take me a little more time to look in and verify if trimming the `baseUrl` would solve this, but most likely yes so I guess you can open a PR for this.
