### ISSUE TITLE
CSS remote imports do not work in Non SSR mode

### ISSUE THREAD

**Issue by FallingSnow** [alephjs/aleph.js#126]
Add tailwindcss, then add a class. This class is applied in SSR but not SSG.

Repo: https://github.com/FallingSnow/alephjs-issue

Code:
```js
<div className="page bg-red-400">
logo
</div>
```

SSG:
![Screenshot from 2021-02-05 11-12-16](https://user-images.githubusercontent.com/2512197/107078329-09ff7980-67a3-11eb-810f-fb43db3b79ab.png)

SSR:
![Screenshot from 2021-02-05 11-13-14](https://user-images.githubusercontent.com/2512197/107078409-2996a200-67a3-11eb-81e4-e7aaf475e468.png)

**Comment by hazae41** [comment]
Same issue, it seems <link/> are not applied when using SPA mode (SSR false)

**Comment by shadowtime2000** [comment]
Does using a static `import` work?

**Comment by hazae41** [comment]
> Does using a static `import` work?

No, the page don't even load, I get a blank page with this in the console

![Capture](https://user-images.githubusercontent.com/4405263/107774999-0b4f1a00-6d40-11eb-99f7-10194b398cff.PNG)

(Yes I deleted the .aleph folder)

**Comment by hazae41** [comment]
> Does using a static `import` work?

It also fails in SSR mode (SSR true)

> TypeError: Cannot resolve module "file:///.../.aleph/development/-/esm.sh/tailwindcss/dist/tailwind.min.css" from "file:///.../.aleph/development/app.ab9f7c998.js".
    at file:///.../.aleph/development/app.ab9f7c998.js:8:0

**Comment by ije** [comment]
i'm writing the loader system, will fix this next patch

**Comment by ije** [comment]
close ref #388
