### ISSUE TITLE
Issue using `useDeno` in 0.3.0

### ISSUE THREAD

**Issue by juanvillacortac** [alephjs/aleph.js#127]
Throws:
```
TypeError: Cannot read property 'value' of undefined
    at http://localhost:8080/_aleph/-/deno.land/x/aleph@v0.3.0-alpha.6/framework/react/hooks.js:88:28
    at mountMemo (http://localhost:8080/_aleph/-/cdn.esm.sh/v15/react-dom@17.0.1/esnext/react-dom.development.js:12623:33)
    at Object.useMemo (http://localhost:8080/_aleph/-/cdn.esm.sh/v15/react-dom@17.0.1/esnext/react-dom.development.js:12930:36)
    at useMemo2 (http://localhost:8080/_aleph/-/cdn.esm.sh/v15/react@17.0.1/esnext/react.development.js:1104:35)
    at useDeno (http://localhost:8080/_aleph/-/deno.land/x/aleph@v0.3.0-alpha.6/framework/react/hooks.js:54:12)
    at App (http://localhost:8080/_aleph/app.a3093224d.js:21:5)
    at renderWithHooks (http://localhost:8080/_aleph/-/cdn.esm.sh/v15/react-dom@17.0.1/esnext/react-dom.development.js:12007:32)
    at mountIndeterminateComponent (http://localhost:8080/_aleph/-/cdn.esm.sh/v15/react-dom@17.0.1/esnext/react-dom.development.js:14188:29)
    at beginWork (http://localhost:8080/_aleph/-/cdn.esm.sh/v15/react-dom@17.0.1/esnext/react-dom.development.js:14987:36)
    at HTMLUnknownElement.callCallback2 (http://localhost:8080/_aleph/-/cdn.esm.sh/v15/react-dom@17.0.1/esnext/react-dom.development.js:4265:34)
```

Code to reproduce:
```jsx
import type { ComponentType } from 'https://esm.sh/react@17.0.1'
import React from 'https://esm.sh/react@17.0.1'
import { useDeno } from 'https://deno.land/x/aleph@v0.3.0-alpha.6/mod.ts'

export default function App({ Page, pageProps }: { Page: ComponentType<any>, pageProps: any }) {
  useDeno(() => {
    console.log('Hi')
  })
  return (
    <main>
      <Page {...pageProps} />
    </main>
  )
}
```

**Comment by ije** [comment]
@juanvillacortac can you please upgrade to **alpha.7** and try again, i think it has be fixed. Thanks!

```
aleph upgrade
```

**Comment by juanvillacortac** [comment]
Now `useDeno` hook works without crash, but returns `null` always. I'm on **0.3.0-alpha.8**

**Comment by juanvillacortac** [comment]
I'm debugging and I found that SSR generated keys are inserted on server `globalThis`, but not on browser `globalThis`.

**Comment by juanvillacortac** [comment]
I'm debugging and I found that SSR generated keys are inserted on server `globalThis`, but not on browser `globalThis`.

**Comment by shadowtime2000** [comment]
@juanvillacortac Ooh thanks. I think that helps us a lot. btw deleted a comment by you because it must have been a github glitch or something and the helpful information you were giving got duplicated into 2 messages.

**Comment by juanvillacortac** [comment]
Sorry, the messages are sended twice because my internet are unstable and Github bugged. PD: Sorry for my english.

**Comment by ije** [comment]
thanks @juanvillacortac , we should use `window` instead of `globalThis` since deno also support it, my mistake

**Comment by shadowtime2000** [comment]
> thanks @juanvillacortac , we should use `window` instead of `globalThis` since deno also support it, my mistake

@ije I don't think the problem lies in that - `globalThis` is supported in most browsers too, seems to be more of the problem of them only being injected on server side while not being injected on the browser side.

**Comment by shadowtime2000** [comment]
[`globalThis` on Can I Use](https://caniuse.com/mdn-javascript_builtins_globalthis) - has support in all modern browsers

**Comment by juanvillacortac** [comment]
Yes, `globalThis` is supported in both, but I don't think that its props are shared between browser and server, but I don't know if `window` object is also shared between both contexts.

**Comment by ije** [comment]
in the client, the **useDeno** data will be inject to globalThis before page rendering.

**Comment by ije** [comment]
@juanvillacortac can you please post the source code?

**Comment by ije** [comment]
@shadowtime2000 yeah, will add the **globalThis** polyfill for _IE11_.

**Comment by juanvillacortac** [comment]
@ije Yes, please inspect this repo: [https://github.com/pixelwall/xd-dogs](https://github.com/pixelwall/xd-dogs)

**Comment by juanvillacortac** [comment]
I'm testing, and in SSG mode `useDeno` values are filled correctly. In production mode with `aleph start` doesn't work like in `aleph dev` mode, only in SSG.

**Comment by juanvillacortac** [comment]
PD: I'm deleteting `.aleph` folder for force new cache.

**Comment by ije** [comment]
@juanvillacortac i saw your project, it is cool! good job. my question is the `ALEPH_ENV` key you are using is existing in your system env? 
![image](https://user-images.githubusercontent.com/2883484/107151875-f40ad800-699f-11eb-9645-d6de6cda128c.png)
![image](https://user-images.githubusercontent.com/2883484/107151864-e6555280-699f-11eb-8f4a-f37b777e8c92.png)

**Comment by juanvillacortac** [comment]
@ije Yes, I fill the env variables with the Makefile (and the dev and deploy workflow are managed with `make`). The `useDeno` values works in server environment, but if you try to access those values on browser are always null, but, the SSG mode is the only way that `useDeno` works as expected.

**Comment by juanvillacortac** [comment]
Hello again. I notice that `useDeno` retrieve the correct value only when is used in a view component under `pages` folder, and also work in `app.tsx` file if we are viewing a page with `useDeno` inside, but if we doesn't have used `useDeno` in a route (and viewing that route) `useDeno` doesn't work correctly inside `app.tsx`.

**Comment by ije** [comment]
@juanvillacortac yes, i also figured out, currently only use `useDeno` in page components will generate the ssr data, i will fix it ASAP. thanks
