### ISSUE TITLE
Missing Styles in Production Mode

### ISSUE THREAD

**Issue by juanvillacortac** [alephjs/aleph.js#130]
`aleph dev`:

![image](https://user-images.githubusercontent.com/37244056/107124491-a21c6200-687a-11eb-968a-4face80c6a92.png)

`aleph start` | `aleph build`:

![Screenshot 2021-02-06 at 12 51 56 PM](https://user-images.githubusercontent.com/37244056/107124459-697c8880-687a-11eb-9750-b9d08932d3b8.png)

Content of `app.tsx`:

```tsx
import './style/index.css'
import type { ComponentType } from 'react'
import React, { useEffect } from 'react'
import { useDeno } from 'aleph'
import wf from 'https://esm.sh/webfontloader@1.6.28'
import { initSW } from './lib/sw.ts'

export default function App({ Page, pageProps }: { Page: ComponentType<any>, pageProps: any }) {
  const dev = useDeno(() => Deno.env.get('ALEPH_ENV')) === 'development'
  useEffect(() => {
    if (navigator) {
      initSW(dev)
    }
    if (typeof window !== 'undefined') {
      wf.load({
        google: {
          families: ['Roboto:300,400,800,900', 'Merriweather+Sans:300,400,800,900', 'Inconsolata']
        }
      })
    }
  })
  return (
    <main>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <title>XD Dogs</title>
      </head>
      <Page {...pageProps} />
    </main>
  )
}
```

**Comment by ije** [comment]
@juanvillacortac thanks, i will check out later !

**Comment by juanvillacortac** [comment]
I'm deleted the `.aleph` folder and the problem is solved. I think is a problem with caching in SSR, I don't know.

**Comment by shadowtime2000** [comment]
Majority of the problems seem to be solved when deleted the `.aleph` cache - possibly with cache not changing on version updates or something?

**Comment by ije** [comment]
close ref #388
