### ISSUE TITLE
Can't use markdown file as page 

### ISSUE THREAD

**Issue by KylinLee** [alephjs/aleph.js#131]
Aleph.js v0.3.0-alpha.1

I use `aleph init` to create my project, and create a markdown file in `pages` dir.

like this

```
pages
├── about.md
├── index.tsx
└── post
    └── index.tsx
```

when I run `aleph dev` to start the server, I got such message, when I visit `/about`, it returns 404, when I visite `/about.md`, it throw an Error.

<img width="654" alt="2021-02-07_19-04-40" src="https://user-images.githubusercontent.com/44860097/107144734-1c7edc00-6978-11eb-9785-8b7bed744c20.png">

**Comment by ije** [comment]
@KylinLee, please note that we already removed the builtin markdown page routing in **0.3**, i will update docs later.

**Comment by ije** [comment]
but a plugin will be added to support markdown pages in the future.

**Comment by KylinLee** [comment]
> but a plugin will be added to support markdown pages in the future.

Thanks
