### ISSUE TITLE
"assert" module throws SyntaxError

### ISSUE THREAD

**Issue by hazae41** [alephjs/aleph.js#132]
Hey, I just upgraded to Aleph 3.0 alpha 8 and Deno 1.7.2 (was on 1.6.3)

But when entering "aleph dev", the following error is thrown by the "assert" module (which is imported by a library I use):

> ERROR TypeError: Uncaught SyntaxError: Unexpected token '&&'
        return n ?? r.has(n) && !e.has(n);
> at <anonymous> (.../.aleph/development/-/cdn.esm.sh/v15/assert@2.0.0/esnext/assert.js:2020:30)

![Capture](https://user-images.githubusercontent.com/4405263/107149184-863abe00-6957-11eb-806c-a788fe067581.PNG)

I don't know if it's related to esm.sh or aleph, because this error wasn't there before I upgraded

**Comment by hazae41** [comment]
Just downgraded to Deno 1.6.3 and Aleph 0.2.28, the error is gone

**Comment by ije** [comment]
@hazae41  which lib you are using? i guess it's swc's issue, 0.2.28 is using the tsc.

**Comment by hazae41** [comment]
@ije It seems to be imported by https://esm.sh/@ethersproject/providers

**Comment by ije** [comment]
thanks, i will look into it!

**Comment by hazae41** [comment]
Nevermind, it seems the bug was coming from a module I was importing using ES2020 target (added automatically by VSCode auto import?)

The following (es2020) throws an error

```typescript
import WalletConnect from "https://cdn.esm.sh/v15/@walletconnect/web3-provider@1.3.4/es2020/web3-provider.js"
```

The following (es2018) does not

```typescript
import WalletConnect from "https://cdn.esm.sh/v15/@walletconnect/web3-provider@1.3.4/es2018/web3-provider.js"
```

The following does not

```typescript
import WalletConnect from "https://esm.sh/@walletconnect/web3-provider"
```
