### ISSUE TITLE
Auto Refresh not working in 0.3.0-alpha.8

### ISSUE THREAD

**Issue by borsemayur2** [alephjs/aleph.js#133]
I'm required to refresh the page manually on win 10 (was working previously) after upgrading Aleph (from v0.3.0-alpha.4 to v0.3.0-alpha.8)

**Comment by borsemayur2** [comment]
Auto refresh works with Deno 1.7.2 and Aleph v0.3.0-alpha.4

**Comment by borsemayur2** [comment]
Fix isn't working for me

**Comment by ije** [comment]
will release the patch later, sorry i just came back from vacation

**Comment by borsemayur2** [comment]
@ije Okay. Thanks

**Comment by FallingSnow** [comment]
@borsemayur2 is this the same behavior as #120?

**Comment by borsemayur2** [comment]
No. HMR works now, but I still have to refresh the page manually after code change for the latest aleph.

**Comment by borsemayur2** [comment]
Auto refresh works now. Thanks
