### ISSUE TITLE
TypeError: Cannot destructure 'applyCSS(...)'  on WSL

### ISSUE THREAD

**Issue by borsemayur2** [alephjs/aleph.js#134]
Not able to run the demo app on WSL while the same code runs on win 10
![image](https://user-images.githubusercontent.com/47341981/107170698-0e1bd900-69e7-11eb-9f9c-a606509d36c6.png)

**Comment by borsemayur2** [comment]
Versions:
Deno: 1.7.2
Aleph: v0.3.0-alpha.8

**Comment by ije** [comment]
@borsemayur2 didn't test on WLS...will do it later, thanks 👍

**Comment by ije** [comment]
close ref #388
