### ISSUE TITLE
Wrong import.meta.url when caching

### ISSUE THREAD

**Issue by hazae41** [alephjs/aleph.js#136]
Hey, I try use a module that dynamically imports a .wasm file

https://deno.land/x/ed25519_dalek@1.0.2/legacy.ts

The problem is that the module uses import.meta.url to import the relative .wasm file

```typescript
const url = new URL(path, import.meta.url);
```

But when Aleph caches that module, the wasm file is not cached

When using the module, the module fails to find the .wasm file (404)

```typescript
import { ... } from "https://deno.land/x/ed25519_dalek@1.0.1/legacy.ts" 
```

![Capture](https://user-images.githubusercontent.com/4405263/107406192-76aea700-6b08-11eb-882a-d401b091f3c7.PNG)

The workaround I use is making my own mod.ts file, and modify it to fetch the .wasm file from deno.land

```typescript
export {
  Ed25519Keypair,
  Ed25519PublicKey,
  Ed25519Signature
} from "https://deno.land/x/ed25519_dalek/pkg/denoed25519.js"

import init from "https://deno.land/x/ed25519_dalek/pkg/denoed25519.js"

async function read(path: string) {
  const url = new URL(path, import.meta.url);

  if (url.protocol === "file:") {
    return await Deno.readFile(url);
  }

  const res = await fetch(url)
  return await res.arrayBuffer();
}

export default (async () => {
  await init(read("https://deno.land/x/ed25519_dalek@1.0.2/pkg/denoed25519_bg.wasm"));
})()
```

**Comment by shadowtime2000** [comment]
Instead of trying to cache the WASM file too we could just replace `import.meta.url`
