### ISSUE TITLE
Cannot build: Unable to output bundle during Graph::bundle()

### ISSUE THREAD

**Issue by hazae41** [alephjs/aleph.js#138]
My app works flawlessly using "aleph dev", but when I try "aleph start" or "aleph build", I face this error

> INFO - Bundling
INFO   {} polyfill (ES5) • 8KB
INFO   {} deps • 3.2MB
Bundle .../.aleph/production/shared.bundle.entry.js
error: Unable to output bundle during Graph::bundle().

I've tried to clear the .aleph cache, the error still happens

**Comment by ije** [comment]
@hazae41 can you please check the  `.aleph/shared.bundle.entry.js`, thanks

**Comment by hazae41** [comment]
.aleph\production\shared.bundle.entry.js

```typescript
import * as shared_mod_0 from "file://...\\.aleph\\production\\app.bundling.d9f226493.js"
__ALEPH.pack["/app.tsx"] = shared_mod_0
```

**Comment by ije** [comment]
@hazae41 i will fix it ASAP

**Comment by ije** [comment]
now we use esbuild bundle the dist, this should never happen again.
