### ISSUE TITLE
How to access query params passed to api action (dynamic routes)

### ISSUE THREAD

**Issue by borsemayur2** [alephjs/aleph.js#139]
I'm writing Todos APIs. I need to pass `id` of the todo record for `retrieve`, `update` and `delete` action. 

How Should I pass the `id` ?
`/todos/retrieve/1 ` or `/todos/retrieve?id=1`

How can I access the passed `id`?
request.params contains `{action: 'retrieve'}` only

**Comment by shadowtime2000** [comment]
Please use discussions for questions. You can use the `useRouter` hook to collect information from queries and other stuff.
