### ISSUE TITLE
Self recommendation of transformer related libraries

### ISSUE THREAD

**Issue by Jack-Works** [alephjs/aleph.js#14]
Hi! This library is cool, thanks for your work! When I view the source code, I found I can provide some better alternatives to some TS transformers.

React Refresh TS transformer: [react-refresh-typescript](https://www.jsdelivr.com/package/npm/react-refresh-typescript) [(PR to React)](https://github.com/facebook/react/pull/19914)

`react-refresh-typescript` is provided in both [ESM](https://cdn.jsdelivr.net/npm/react-refresh-typescript@1.0.4/index.mjs) and CommonJS format. This package doesn't depend on any Node-JS specific functionalities. It's fully passed the test suit as the babel version does.

Import path rewrite: [@magic-works/ttypescript-browser-like-import-transformer](https://github.com/Jack-Works/ttypescript-browser-like-import-transformer#emit-a-es-module-web-project-by-only-ttypescript) is a fully functional import path rewrite library for converting any imports to Web-ready imports. This library also considers the non-Node environment in mind when design. All IO (including `import` statements) are delegated to a `node` adaptor so if you need it, I can write a `deno` adaptor and it's available for `deno`.

Thanks!

**Comment by ije** [comment]
this is fabulous!!! the `react-refresh` transform in Aleph.js is not stable currently, your library definitely is the thing i was looking for! 

```javascript
import reactReFreshTypescrpt from "https://esm.sh/react-refresh-typescript"
```

this should work, i will test it later, great work thanks a lot!

**Comment by ije** [comment]
currently i'm focusing on Aleph.js's new compiler with [swc](https://swc.rs/) in Rust to get better prefs since **tsc** is slow, also needs a stable fast refresh plugin for the new compiler, would you be interested in the plugin in swc(Rust)? 

FYI please check the [swc branch](https://github.com/alephjs/aleph.js/tree/swc)

**Comment by Jack-Works** [comment]
I know swc but never write a plugin for it. I may have a try 👀

**Comment by ije** [comment]
@Jack-Works i just tested, something unexpected was going to happen.

**compile.ts**
```javascript
import reactRefreshTS from 'https://esm.sh/react-refresh-typescript@1.0.4'

transformers.before!.push(reactRefreshTS({}))
```
**logo.tsx**
```jsx
import React, { useState } from 'https://esm.sh/react'

export default function Logo({ width = 75 }: { width?: number }) {
   const [height, setHeight] =  useState(width)


    return (
        <img src="/logo.svg" width={width} height={height} title="Aleph.js" />
    )
}
```

i got an unfinished result:
```javascript
var _a;
import React, { useState } from "../-/esm.sh/react.js";
export default function Logo({ width = 75 }) {
    const [height, setHeight] = useState(width);
    return (React.createElement("img", { src: "/logo.svg", width: width, height: height, title: "Aleph.js", __source: { fileName: "/components/logo.tsx", lineNumber: 7 } }));
}
_a = Logo;
$RefreshReg$(_a, "Logo");
```

should be:
```javascript
const _s = $RefreshSig$();
import React, { useState } from "../-/esm.sh/react.js";
export default function Logo({ width = 75 }) {
    _s();
    const [height, setHeight] = useState(width);
    return (React.createElement("img", { src: "/logo.svg", width: width, height: height, title: "Aleph.js", __source: { fileName: "/components/logo.tsx", lineNumber: 6 } }));
}
_s(Logo, "useState{[height, setHeight](width)}");
$RefreshReg$(Logo, "Logo");
```

anything i missed?

**Comment by Jack-Works** [comment]
Hooks signature are missing, strange, I'll investigate it later

**Comment by ije** [comment]
cool, thanks

**Comment by Jack-Works** [comment]
Sorry I cannot reproduce that. My result for your example code is:

```js
"use strict";
var _a;      
var _b;      
_b = $RefreshSig$();
Object.defineProperty(exports, "__esModule", { value: true });
var react_1 = require("https://esm.sh/react");
function Logo(_c) {
    var _d = _c.width, width = _d === void 0 ? 75 : _d;
    _b();
    var _e = react_1.useState(width), height = _e[0], setHeight = _e[1];
    return (react_1.default.createElement("img", { src: "/logo.svg", width: width, height: height, title: "Aleph.js" }));
}
exports.default = Logo;
_a = Logo;
$RefreshReg$(_a, "Logo");
_b(Logo, "B1bTgemxQeKxhnx7iLvvyxMpH2Y=");
```

```js
const ts = require("typescript");
const x = require("typescript");
const result = x.transpileModule(
    `import React, { useState } from 'https://esm.sh/react'

    export default function Logo({ width = 75 }: { width?: number }) {
       const [height, setHeight] =  useState(width)
    
    
        return (
            <img src="/logo.svg" width={width} height={height} title="Aleph.js" />
        )
    }
    `,
    { transformers: { before: [require("./index").default()] }, compilerOptions: { jsx: ts.JsxEmit.React } }
).outputText;
console.log(result);
```

**Comment by ije** [comment]
@Jack-Works i changed the transformers order(seems **react-refresh-typescript** should be the first one), it works now!

```javascript
var _a;
var _b;
_b = $RefreshSig$();
import React, { useState } from 'https://esm.sh/react';
export default function Logo({ width = 75 }) {
    _b();
    const [height, setHeight] = useState(width);
    return (React.createElement("img", { src: "/logo.svg", width: width, height: height, title: "Aleph.js" }));
}
_a = Logo;
$RefreshReg$(_a, "Logo");
_b(Logo, "B1bTgemxQeKxhnx7iLvvyxMpH2Y=");
```
what a feat! thanks!
