### ISSUE TITLE
This page cannot be accessed outside the docker container (http://0.0.0.0:8080/http://172.17.0.2:8080)

### ISSUE THREAD

**Issue by jiclivi** [alephjs/aleph.js#143]
Visiting 8080 in the docker container can output Hello World-Aleph.js
but outside the container (http://0.0.0.0:8080/http://172.17.0.2:8080) this page cannot be accessed

aleph start
INFO Building...
INFO - Bundling
INFO   {} deps • 159KB
INFO   {} shared • 398B
INFO   {} polyfill (ES5) • 8KB
INFO Aleph server ready on http://localhost:8080

**Comment by jiclivi** [comment]
root@601bcb8deb0d:/aleph$ curl http://localhost:8080
<!DOCTYPE html><html lang="en"><head><meta charSet="utf-8" /><title ssr>Hello World - Aleph.js</title> ......

![20210212113458](https://user-images.githubusercontent.com/14210650/107727544-860b3b80-6d26-11eb-8b7f-390fcd7e5195.png)

**Comment by shadowtime2000** [comment]
I know nothing about docker containers and stuff like that (im a full on jamstack person :P) so I guess this something that could be fixed/solved by someone with more experience in this.

**Comment by jiclivi** [comment]
@shadowtime2000 
Need to modify the localhost to 0.0.0.0
aleph start -hn 0.0.0.0 -p 8080

**Comment by ije** [comment]
@jiclivi so basically we should change the default hostname to 0.0.0.0 can fix this？https://github.com/alephjs/aleph.js/blob/fd347a7cb5c4614101911dd2b97dea06e676516c/cli/start.ts#L26

**Comment by shadowtime2000** [comment]
Not a docker expert at all but if that can fix it maybe it would be possible to create our own docker file config thingy based off of @hayd's one and have it by default set the hostname to 0.0.0.0

**Comment by jiclivi** [comment]
@ije Yes it is
Need to modify localhost to 0.0.0.0

**Comment by ije** [comment]
@jiclivi great! thanks! can you please make a pr? or I will do it later, thanks

**Comment by jiclivi** [comment]
> @jiclivi great! thanks! can you please make a pr? or I will do it later, thanks
I just learned deno, the environment I use is docker ubuntu vim to write alephjs

**Comment by ije** [comment]
@jiclivi cool, i will release a patch later

**Comment by jiclivi** [comment]
@ije Can you get such an admin?
https://preview.pro.ant.design/dashboard/analysis?fixSiderbar=true&colorWeak=false&pwa=false

Base Layout：
![20210219195418](https://user-images.githubusercontent.com/14210650/108598758-6df08780-73ca-11eb-9c5d-3e1d6b54f7c0.png)

**Comment by jiclivi** [comment]
ant design pro , The layout is fixed, not very friendly to custom layouts

A plugin like this is pretty good

![20210220223118](https://user-images.githubusercontent.com/14210650/108599443-210db080-73cc-11eb-8592-9e2c19970d8e.png)

**Comment by borsemayur2** [comment]
@jiclivi  I'm getting `localhost didn’t send any data. ERR_EMPTY_RESPONSE` while running `aleph start -hn 0.0.0.0 -p 8080` in docker container. What am I missing?

**Comment by jiclivi** [comment]
@borsemayur2  docker run  -p 8080:8080

docker No external port mapping specified

**Comment by borsemayur2** [comment]
![image](https://user-images.githubusercontent.com/47341981/108653632-f6ffdf80-74ec-11eb-85b6-499fd39ffd6b.png)
This is the port mapping. Looks fine?

**Comment by jiclivi** [comment]
> ![image](https://user-images.githubusercontent.com/47341981/108653632-f6ffdf80-74ec-11eb-85b6-499fd39ffd6b.png)
> This is the port mapping. Looks fine?

Try the container ip: 8080
query docker ip(docker inspect container | grep "Add")

**Comment by borsemayur2** [comment]
![image](https://user-images.githubusercontent.com/47341981/108660427-fd905600-74f0-11eb-950d-de67fea1d937.png)
Getting this output.

**Comment by jiclivi** [comment]
> ![图像](https://user-images.githubusercontent.com/47341981/108660427-fd905600-74f0-11eb-950d-de67fea1d937.png)
> 获取此输出。

![20210222120605](https://user-images.githubusercontent.com/14210650/108661304-7352ec80-7506-11eb-80c0-5830d9110c40.png)

**Comment by jiclivi** [comment]
![20210222120753](https://user-images.githubusercontent.com/14210650/108661421-c4fb7700-7506-11eb-9bb4-3a7b21b1120c.png)

**Comment by jiclivi** [comment]
@borsemayur2 
I created the docker environment like this

docker run -it --name=gui-vim-code \
  -p 80:80 \
  -p 8080:8080 \
  -p 5000:5000 \
  -p 8899:8899 \
  --mount "type=bind,src=/home/jclivi/Desktop/works/work,dst=/work-path" \
  --workdir /work-path \
  -v /etc/localtime:/etc/localtime:ro \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  -e DISPLAY=unix$DISPLAY \
  -e GDK_SCALE \
  -e GDK_DPI_SCALE \
  gui-vim-code:0.3 /bin/bash

**Comment by jiclivi** [comment]
@borsemayur2 

1. docker mount deno
docker run -it --name=aleph-test \
  -p 80:80 \
  -p 8080:8080 \
  -p 5000:5000 \
  -p 8899:8899 \
  --mount "type=bind,src=/home/user/Desktop/works/deno,dst=/work-path/deno" \
  --workdir /work-path \
  -v /etc/localtime:/etc/localtime:ro \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  -e DISPLAY=unix$DISPLAY \
  -e GDK_SCALE \
  -e GDK_DPI_SCALE \
  ubuntu /bin/bash

2. modify ~/.bashrc
############### deno
###############
export DENO_INSTALL=$USERPATH/config/language/deno
export DENO_DIR=$DENO_INSTALL/.deno/cache
export PATH=$PATH:$DENO_INSTALL/bin:$DENO_DIR

3. deno install aleph
aleph start -hn 0.0.0.0 -p 8080

**Comment by borsemayur2** [comment]
I'll give it a try. Thanks

**Comment by borsemayur2** [comment]
@jicvi #193 This is the reason I'm not able to run app in docker on Win 10 and WSL. Your code works on macOS. Thanks

**Comment by borsemayur2** [comment]
@ije @jicvi Docker works for me with HMR and `aleph dev` with v3.0.0-alpha.12. Thanks
