### ISSUE TITLE
[0.3.0-alpha.8] Error on bundle from static build

### ISSUE THREAD

**Issue by juanvillacortac** [alephjs/aleph.js#150]
Web app prerenderize correctly, but javascript doesn't load, and this is the error throwed on dev tools:

![image](https://user-images.githubusercontent.com/37244056/107855476-e1a5f980-6df8-11eb-8ace-7c8512ea4756.png)

I think that there is not a chunk module generated for `app.tsx` file, but app still need import this file, and throws a 404 error.

**Comment by juanvillacortac** [comment]
File structure from generated build:

- Under `_aleph`:

![image](https://user-images.githubusercontent.com/37244056/107855576-a7892780-6df9-11eb-82a7-36dafef7e62c.png)

- Under `_aleph/pages`:

![image](https://user-images.githubusercontent.com/37244056/107855595-c5568c80-6df9-11eb-90b0-5a930ae4298e.png)

- Under `_aleph/data`:

![image](https://user-images.githubusercontent.com/37244056/107855608-dd2e1080-6df9-11eb-903d-a2ab062bc604.png)

Note that there is no `app.${hash}.js`

**Comment by ije** [comment]
@juanvillacortac thanks, i'm rewriting the loader and bundling system to make it more stable.

**Comment by ije** [comment]
now we are use esbuild to bundle the dist, this should be fixed
