### ISSUE TITLE
[0.3.0-a.8] fail run in development / build mode, by "FATAL 'pages' directory not found."

### ISSUE THREAD

**Issue by Stvchm9703** [alephjs/aleph.js#152]
# environment 
OS : MacOs 15.5.7

deno : 1.7.4
aleph.js : v0.3.0-alpha.8

# how it case 
I just init the project by running `aleph init` 

it comes out the project structure
<img width="190" alt="Screenshot 2021-02-17 at 2 30 40 PM" src="https://user-images.githubusercontent.com/15327054/108164988-c4409a80-712c-11eb-9015-0096e1a6f586.png">

then I run `aleph dev` / `aleph build`
it show the `FATAL 'pages' directory not found.`

**Comment by ije** [comment]
did you change to the `aleph-static` dir?

**Comment by Stvchm9703** [comment]
did you change to the aleph-static dir? << nope , all I run is as same as 'get start' in tutor
