### ISSUE TITLE
[0.3.0-alpha.8] "Minified React error #321" while running `aleph build`

### ISSUE THREAD

**Issue by oyzhen** [alephjs/aleph.js#153]
![image](https://user-images.githubusercontent.com/52534412/108320036-400a1800-71fd-11eb-84eb-bb723ee4ddd2.png)

React error #321 refs:
https://reactjs.org/docs/error-decoder.html/?invariant=321

![image](https://user-images.githubusercontent.com/52534412/108320352-a98a2680-71fd-11eb-9250-0bfe524a10db.png)

**Comment by shadowtime2000** [comment]
@oyzhen Can you share a reproduction repo? It could be because you are importing a lib from esm.sh which uses React 16 when we use React 17.

**Comment by oyzhen** [comment]
The project was just generated by `aleph init`.
And the 'import_map.json' is: 
```json
{
    "imports": {
        "~/": "./",
        "@/": "./",
        "aleph": "https://deno.land/x/aleph@v0.3.0-alpha.8/mod.ts",
        "aleph/": "https://deno.land/x/aleph@v0.3.0-alpha.8/",
        "react": "https://esm.sh/react@17.0.1",
        "react-dom": "https://esm.sh/react-dom@17.0.1"
    },
    "scopes": {}
}
```

My deno version is 1.7.1

I tried 'deno run --reload -A https://deno.land/x/aleph@v0.3.0-alpha.8/cli.ts build', still error.

**Comment by shadowtime2000** [comment]
@oyzhen Was it just the basic default template?

**Comment by oyzhen** [comment]
Yes.

**Comment by ije** [comment]
@oyzhen please try `aleph build --reload`

**Comment by oyzhen** [comment]
> @oyzhen please try `aleph build --reload`

@ije Great! Thanks a lot!
