### ISSUE TITLE
NPM package import from skypack, jsdelivr, jspm fails (only esm.sh works)

### ISSUE THREAD

**Issue by borsemayur2** [alephjs/aleph.js#154]
For material ui package.

Deno: 1.7.4
Aleph: v0.3.0-alpha.8

**Comment by borsemayur2** [comment]
Using import-map

**Comment by shadowtime2000** [comment]
@borsemayur2 Can you provide reproduction steps or a reproduction repository? And how is the fact that only esm.sh works with it an issue?

**Comment by ije** [comment]
since alephjs use esm.sh import react lib, if you use some packages in skypack that depend on react will import a different react instance

**Comment by ije** [comment]
i will imporve the compiler to support those CDNs in the future, for now please use esm.sh

**Comment by ije** [comment]
the main problem is those CDN dont provide dev build that is alephjs required to support fast-refresh and full console log output.

**Comment by borsemayur2** [comment]
@shadowtime2000 `"@material-ui/core": "https://esm.sh/@material-ui/core" `with any of the mentioned CDNs in `import_map.json`. I only wanted to inform about other CDNs not working.

@ije Okay. I'm fine with esm.sh. Just wanted to try out other CDNs.

Thanks
