### ISSUE TITLE
polyfills usage

### ISSUE THREAD

**Issue by ije** [alephjs/aleph.js#156]
parse AST at compilation phase to create a minimum polyfills by usages.

**Comment by shadowtime2000** [comment]
@ije Are the polyfills in the compiler folder just injected into it?

We could just write some polyfills inside the `compiler/polyfills` folder and have the compiler transform object accessors and stuff rewrite to usages of imports of them.

**Comment by ije** [comment]
i think the compiler should return a polyfills usage list to the bundler, then bundle the polyfills to a js fill.

**Comment by shadowtime2000** [comment]
@ije Couldn't we also use the SWC crates that have been published for stuff like this?

**Comment by ije** [comment]
which crate?

**Comment by shadowtime2000** [comment]
@ije I think we could use [swc_ecma_transforms_compat](https://crates.io/crates/swc_ecma_transforms_compat).

**Comment by shadowtime2000** [comment]
@ije Do you think we could use [swc_bundler](https://crates.io/crates/swc_bundler) instead of using `Deno.run` and `deno bundle`?

**Comment by ije** [comment]
@shadowtime2000 no, we should use Deno.run instead of swc_bundler wasm, unless the deno plugin op is stable

**Comment by shadowtime2000** [comment]
@ije What do you think about instead using `Deno.emit`? Still trying to piece together how the rust wasm compiler is organized but i think we could use `swc_ecma_transforms_compat`.

**Comment by ije** [comment]
@shadowtime2000 the bundler is using `swc_ecma_transforms_compat` now, but some polyfills should be added like `fetch`, `Array.prototype.includes`, `Promise.All`, etc...
FYI https://github.com/alephjs/aleph.js/blob/master/compiler/src/swc.rs#L16

**Comment by ije** [comment]
the `deno bundle` is the best way i tried

**Comment by ije** [comment]
for now it is, maybe in the future we can use the deno plugin op instead of wasm that can access the file system and support multi-thread.

**Comment by shadowtime2000** [comment]
@ije I believe if we used WASI we could directly access files with WASM
