### ISSUE TITLE
vscode setting is wrong

### ISSUE THREAD

**Issue by ufoo68** [alephjs/aleph.js#157]
In aleph project `.vscode/setting.js` is following.

```json
{
      'deno.enable': true,
      'deno.unstable': true,
      'deno.import_map': './import_map.json'
}
```

However, referenced [deno vscode extension](https://marketplace.visualstudio.com/items?itemName=denoland.vscode-deno) , 
the following seems to be correct.

```json
{
      'deno.enable': true,
      'deno.unstable': true,
      'deno.importMap': './import_map.json'
}
```

**Comment by Hunam6** [comment]
This can be closed now
