### ISSUE TITLE
cleanPath outputting \\ instead of /

### ISSUE THREAD

**Issue by kuhlaid** [alephjs/aleph.js#164]
The cleanPath function seems to be inserting double backslashes instead of a single forward slash in the main html file. For example the server/helper.ts file is generating the modulepreload javascript link using

`<link rel="modulepreload" href=${JSON.stringify(util.cleanPath(v.src))} />`

which outputs as:

`<link rel="modulepreload" href="\\_aleph\\main.[someval].js" />`

which instead should be:

`<link rel="modulepreload" href="/_aleph/main.[someval].js" />`

The reason I bring this up is when I try to run the hello world locally I get errors that the main.[someval].js cannot be accessed, because the HTML is treating the link as a local file resource and not a HTTP resource. I noticed the sample app at [https://alephjs-hello-world.vercel.app/](https://alephjs-hello-world.vercel.app/) has the correct HTML reference using / instead of \\.

**Comment by shadowtime2000** [comment]
Yeah, we noticed this some time ago but I don't think we were able to figure out where exactly it was being converted. Possibly from usage of `std/path`.

**Comment by XDean** [comment]
It's there a quick workaround? I'm suffering this issue too.

**Comment by shadowtime2000** [comment]
@XDean Unfortunately, there are no workarounds.

**Comment by FallingSnow** [comment]
Are you guys running aleph on Windows?

**Comment by FallingSnow** [comment]
Also, is this the same issue as #138?

**Comment by shadowtime2000** [comment]
> Also, is this the same issue as #138?

@FallingSnow I don't believe so, this issue is regarding the broken dev mode on Windows - I think this is a duplicate issue though.

**Comment by ije** [comment]
i added a testing for the cleanPath, seems it passed the test on window...
https://github.com/alephjs/aleph.js/blob/master/shared/util_test.ts#L53

**Comment by kuhlaid** [comment]
> Also, is this the same issue as #138?

No. This is different. This has to do with how the HTML is output with incorrect HTTP paths (which is not Windows or Linux specific).

**Comment by ije** [comment]
i believe this has be fixed, please upgrade the latest aleph verion, beta is on the way, thanks

**Comment by kotx** [comment]
This seems to be happening on the latest version as well- but with a different part of the code. 
```
import ".\-\deno.land\x\aleph@v0.3.0-beta.12\framework\react\refresh.js";
```
produces
`Uncaught SyntaxError: Invalid hexadecimal escape sequence`

**Comment by ije** [comment]
@kotx thanks, i will look into it!

**Comment by ije** [comment]
fixed in latest release
