### ISSUE TITLE
Cannot assign to read only property 'navigator' of object '#<Window>' error after upgrading Deno to 1.8

### ISSUE THREAD

**Issue by borsemayur2** [alephjs/aleph.js#169]
Aleph app was working with Deno 1.7.5. Getting mentioned error after upgrade
Versions:
Deno: 1.8
Aleph: v0.3.0-alpha.8

**Comment by shadowtime2000** [comment]
@borsemayur2 Can you provide an image of the full error?

**Comment by borsemayur2** [comment]
![image](https://user-images.githubusercontent.com/47341981/109901705-82345e80-7cbf-11eb-97c9-c7c83d910a94.png)
Same for WSL and Win 10

**Comment by shadowtime2000** [comment]
I think this is happening because WebGPU in 1.8.0 is in the `window.navigator` so they sealed it off from modification, but I am not sure.

**Comment by shadowtime2000** [comment]
Looking more into this, it seems `navigator` on Deno only has the webgpu apis so I am going to create an issue in the Deno repo to supply those or allow some modification.

**Comment by shadowtime2000** [comment]
[denoland/deno#9676](https://github.com/denoland/deno/issues/9676).

**Comment by shadowtime2000** [comment]
It appears that you can still modify `navigator`, just not in the way that is currently used so I will try to submit a simple PR by the end of today to fix this.

**Comment by semiautomatix** [comment]
```
deno 1.8.0 (release, x86_64-pc-windows-msvc)
v8 9.0.257.3
typescript 4.2.2
```

```
Check https://deno.land/x/aleph@v0.3.0-alpha.8/cli/dev.ts
error: Uncaught (in promise) TypeError: Cannot assign to read only property 'navigator' of object '#<Window>'
    Object.assign(globalThis, {
           ^
    at Function.assign (<anonymous>)
    at Application.init (https://deno.land/x/aleph@v0.3.0-alpha.8/server/app.ts:410:12)
    at async serve (https://deno.land/x/aleph@v0.3.0-alpha.8/server/server.ts:177:3)
    at async default (https://deno.land/x/aleph@v0.3.0-alpha.8/cli/dev.ts:21:3)
    at async main (https://deno.land/x/aleph@v0.3.0-alpha.8/cli.ts:147:7)
```

Seems to still be an ongoing issue.

**Comment by borsemayur2** [comment]
> 
> 
> ```
> deno 1.8.0 (release, x86_64-pc-windows-msvc)
> v8 9.0.257.3
> typescript 4.2.2
> ```
> 
> ```
> Check https://deno.land/x/aleph@v0.3.0-alpha.8/cli/dev.ts
> error: Uncaught (in promise) TypeError: Cannot assign to read only property 'navigator' of object '#<Window>'
>     Object.assign(globalThis, {
>            ^
>     at Function.assign (<anonymous>)
>     at Application.init (https://deno.land/x/aleph@v0.3.0-alpha.8/server/app.ts:410:12)
>     at async serve (https://deno.land/x/aleph@v0.3.0-alpha.8/server/server.ts:177:3)
>     at async default (https://deno.land/x/aleph@v0.3.0-alpha.8/cli/dev.ts:21:3)
>     at async main (https://deno.land/x/aleph@v0.3.0-alpha.8/cli.ts:147:7)
> ```
> 
> Seems to still be an ongoing issue.

Not working for me either

**Comment by ije** [comment]
@borsemayur2 @semiautomatix yes, alpha.8 is not working in deno 1.8 (deno 1.7 should be fine), @shadowtime2000 's pr has fixed it but there is no tag created since the bundler is breaking...
I changed a lot code for the new plugin & framework system, and totally rewrited the bundler, those changes are making alephjs has better expansibility so we can support other framework like vue at next stage.
also i updated the esm.sh CDN to use deno's `std/node` modules to get better deno compatibility, and it has better downward compatibility after **v23**.

**Comment by borsemayur2** [comment]
> 
> 
> @borsemayur2 @semiautomatix yes, alpha.8 is not working in deno 1.8 (deno 1.7 should be fine), @shadowtime2000 's pr has fixed it but there is no tag created since the bundler is breaking...
> I changed a lot code for the new plugin & framework system, and totally rewrited the bundler, those changes are making alephjs has better expansibility so we can support other framework like vue at next stage.
> also i updated the esm.sh CDN to use deno's `std/node` modules to get better deno compatibility, and it has better downward compatibility after **v23**.

Great. As you have mentioned vue, do we have any plan for svelte?

**Comment by hyochan** [comment]
This is still not working in deno `1.9.2`. Hope I can't any updates notified to use recent `deno`.

**Comment by hyochan** [comment]
Actually, I think I wrote too quickly. Works fine in aleph `0.30.0` and was not working in `0.28.0`.
Deno version is `1.9.2`.

Thanks for the great work!
