### ISSUE TITLE
Can I do a dynamic website with Aleph.js?

### ISSUE THREAD

**Issue by lcswillems** [alephjs/aleph.js#178]
On the documentation, it is written that Aleph.js can do SSR. For me, SSR means "server-side rendering", i.e. that the page is rendering on the server before being served. But `aleph build` always generate a static website. Am I missing something? Can I do a dynamic website with Aleph.js?

**Comment by hazae41** [comment]
You can do both a static and a dynamic website

Static : aleph build
Dynamic: aleph start

https://alephjs.org/docs/get-started
