### ISSUE TITLE
Issue with the documentation of Getting started

### ISSUE THREAD

**Issue by lcswillems** [alephjs/aleph.js#184]
Hi,

I opened this issue yesterday: https://github.com/alephjs/aleph.js/issues/180 . It got closed without explanation whereas there is really an issue. Following the "Getting started" tutorial doesn't lead to a working app.

At least, it should be mentionned to add "--unstable" in the command. But this is not sufficient as I still have this error:

```
Check https://deno.land/x/aleph@v0.2.28/cli/dev.ts
error: Uncaught (in promise) ReferenceError: __filename is not defined
    at de (https://cdn.esm.sh/v16/typescript@4.1.2/deno/typescript.js:10:79336)
    at I (https://cdn.esm.sh/v16/typescript@4.1.2/deno/typescript.js:10:75793)
    at https://cdn.esm.sh/v16/typescript@4.1.2/deno/typescript.js:10:82638
    at https://cdn.esm.sh/v16/typescript@4.1.2/deno/typescript.js:10:82653
    at https://cdn.esm.sh/v16/typescript@4.1.2/deno/typescript.js:10:82849
    at https://cdn.esm.sh/v16/typescript@4.1.2/deno/typescript.js:1:644
    at https://cdn.esm.sh/v16/typescript@4.1.2/deno/typescript.js:247:32680
```

Cf the discussion: https://github.com/alephjs/aleph.js/discussions/181#discussioncomment-451374

**Comment by 1ak31sha** [comment]
ok, ignore what i did above :) i reinstalled deno with unstable flag:
`deno install --unstable -A -f -n aleph https://deno.land/x/aleph@v0.2.28/cli.ts` and now im getting same error as lcswillems

**Comment by 1ak31sha** [comment]
<img width="606" alt="Screen Shot 2021-03-09 at 10 10 35 AM" src="https://user-images.githubusercontent.com/15619911/110491941-bb097480-80bf-11eb-8b95-ff31117afa3f.png">
