### ISSUE TITLE
SWR doesn't work

### ISSUE THREAD

**Issue by pedox** [alephjs/aleph.js#19]
Hi, im trying to using swr using the example from documentation [here](https://alephjs.org/docs/basic-features/import-from-npm) with little bit modifications

```tsx
import useSWR from "https://esm.sh/swr"
import Axios from "https://esm.sh/axios";

const fetcher = (url: string) => Axios.get(url).then(({ data }) => data);

export default function About() {
  const { data } = useSWR('/api/me, fetcher)

  if (!data) {
    return <div>loading...</div>
  }
  return <div>hello {data.name}!</div>
}
```

when i trying to visit that page for the first time, gives me error message, and suddenly commands killed.

```
INFO Server ready on http://localhost:8080
ERROR ReferenceError: navigator is not defined
    at file:///home/hehex/a/.aleph/development.es2018/-/cdn.esm.sh/v4/swr@0.3.8/es2018/swr.development.js:187:55
error: Uncaught ReferenceError: navigator is not defined
    at file:///home/hehex/a/.aleph/development.es2018/-/cdn.esm.sh/v4/swr@0.3.8/es2018/swr.development.js:187:55
```

using Axios works pretty well, i think it because they trying to access navigation object through server side, that supposed to be in browser only.

```ts
var slowConnection = typeof window !== "undefined" && navigator["connection"] && ["slow-2g", "2g"].indexOf(navigator["connection"].effectiveType) !== -1;
```

**Comment by ije** [comment]
you can use Axios with useSWR Hook now, but will get a warning text:

> Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.

i just created a pull request to swr, hope it can fix this.

> https://github.com/vercel/swr/pull/754

**Comment by ije** [comment]
please upgrade the cli command:

```bash
aleph upgrade
```

**Comment by pedox** [comment]
no problems, that looks good!
