### ISSUE TITLE
bug: Crashes on "aleph dev"

### ISSUE THREAD

**Issue by DjDeveloperr** [alephjs/aleph.js#195]
Steps to reproduce:

![img](https://cdn.discordapp.com/attachments/775256647819067404/820562154901078026/unknown.png)

I'm using CLI from `master` branch.

**Comment by shadowtime2000** [comment]
@DjDeveloperr What version of Deno were you on?

**Comment by DjDeveloperr** [comment]
![image](https://user-images.githubusercontent.com/43033058/111062411-90a82480-84ce-11eb-8c92-c44e78eb1545.png)

**Comment by mfortunat0** [comment]
![Screenshot from 2021-03-16 10-54-37](https://user-images.githubusercontent.com/22817703/111321082-5feafb00-8646-11eb-9ce6-d3a9b37e35f4.png)
