### ISSUE TITLE
Request error with Oak

### ISSUE THREAD

**Issue by KotlinIsland** [alephjs/aleph.js#204]
I'm trying to implement Aleph into an existing Oak server but am blocked by react.development.js requests coming back invalid.
```ts
import { Application as Oak } from "https://deno.land/x/oak/mod.ts";
import { Application, Server } from "https://deno.land/x/aleph/server/mod.ts";
import { localProxy } from "https://deno.land/x/aleph/server/localproxy.ts";
import { serve } from "https://deno.land/std@0.91.0/http/server.ts";

localProxy(8080);

const port = 1337;
const hostname = "localhost";
const oak = new Oak();
const app = new Application(".", "development", false);
const server = new Server(app);

oak.use(async (ctx) => {
  await server.handle(ctx.request.serverRequest as any);
});
await oak.listen({ port });

//let s = serve({ port, hostname });
//for await (const r of s) {
//  server.handle(r as any);
//}
```
![image](https://user-images.githubusercontent.com/65446343/112270906-fca43d00-8cc5-11eb-908f-f50e2cba92a0.png)

Looks like the full file isn't being returned for some reason.
Oak on top, std on bottom
![image](https://user-images.githubusercontent.com/65446343/112271258-6fadb380-8cc6-11eb-84fb-29c55e82d047.png)

**Comment by KotlinIsland** [comment]
If I take out the await then react.development.js works, but react-dom.development.js gets a 404.
```ts
oak.use((ctx) => {
  server.handle(ctx.request.serverRequest as any);
});
await oak.listen({ port });
```
![image](https://user-images.githubusercontent.com/65446343/112278790-eb136300-8cce-11eb-95cc-387e6aa3a807.png)

```
WARN ServerRequest.respond: Bad resource ID
```

**Comment by ije** [comment]
@KotlinIsland thanks, i will look into, no testing with oak as middleware

**Comment by KotlinIsland** [comment]
I was able to work around it for now with 
```ts
oak.use(async (ctx, next) => {
  if (
    [
      "react.development.js",
      "react-dom.development.js",
      "refresh.js",
      "bootstrap.js",
    ].some((it) => ctx.request.url.pathname.endsWith(it))
  ) {
    console.log("responding to bad resource id");
    ctx.response.body = Deno.readTextFileSync(
      ".aleph/development/" + ctx.request.url.pathname.substring(8),
    );
    ctx.response.headers.append("Content-Type", "text/javascript");
  } else await next();
});
```

**Comment by KotlinIsland** [comment]
A whole bunch of stuff gets garbled when it ends up in the browser.
![image](https://user-images.githubusercontent.com/65446343/112398924-eabbac00-8d50-11eb-9462-d6b6a4509829.png)

**Comment by KotlinIsland** [comment]
I just figured out how to fix this `ctx.respond = false;` must be specified from Oak.
```ts
oak.use((ctx) => {
  alephServer.handle(ctx.request.serverRequest as any);
  ctx.respond = false;
});
```

**Comment by ije** [comment]
@KotlinIsland thanks, i think we should provide a oka middle directly to handle this, i will look into it

**Comment by aadamsx** [comment]
For high performance situations, is it appropriate to run Aleph as a SSR server and Web API?  Or should we break out the data access into its own Web API and let Aleph just deal with SSR?

**Comment by shadowtime2000** [comment]
@aadamsx Can you clarify what you mean by "Web API"?

**Comment by aadamsx** [comment]
For example, a Restful web server running Deno + Oak that runs in a container and writes and extracts data from a remote MongoDB database. Basically a CRUD data access layer.

**Comment by aadamsx** [comment]
But the said data access layer actually has configuration options and needs a front end for other tasks around the Web API.

So I was thinking of using Aleph for both SSR + Web API.  Again the SSR will have both configuration screens for the Web API (kinda like admin screens) AND have an application component where users can upload templates.  So front and back facing screens.  Then the app needs to be able to perform data operations (maybe more than just CRUD) for the admin side, and have a front side where third parties can integrate with the Web API.

I can give more examples.

**Comment by shadowtime2000** [comment]
@aadamsx So, we are probably going to support having Aleph for full stack - but it is much more performant and organized to seperate the frontend and the backend. That allows you to modify them seperately without getting bogged down on tooling that combines then and since the frontend would either use static files or serverless functions which are fast, the frontend would be fast and not limited by the overhead of serving static files with a normal server.

**Comment by aadamsx** [comment]
Thanks @shadowtime2000 

But within Aleph we have an /api directory where it processes http requests right?  What is the appropriate use case for this "Web API" in the Aleph context?

**Comment by shadowtime2000** [comment]
@aadamsx The /api directory is for serverless functions, like NextJS

**Comment by aadamsx** [comment]
Right, I think serverless is fine (what is serverless in this context but not setting up an express or oak server?), but without CORS support I will not be able to use the api with external sources.  So yeah, I'll need another Deno server.

Thanks again for your feedback @shadowtime2000

**Comment by ije** [comment]
an oak mddileware added: https://github.com/alephjs/aleph.js/blob/master/server/oak.ts

**Comment by KotlinIsland** [comment]
awesome
