### ISSUE TITLE
Question: Is possible use the hooks useDeno on api class?

### ISSUE THREAD

**Issue by vincenzopalazzo** [alephjs/aleph.js#209]
I'm trying to use useDeno hooks in the API code but I start to understand that this is not possible.

I can ask why? or I'm missing somethings?

**Comment by ije** [comment]
@vincenzopalazzo you can use the `withDeno` hoc or create your own hoc wrapper.
fyi: https://github.com/alephjs/aleph.js/blob/master/framework/react/hoc.ts#L38
