### ISSUE TITLE
Can't export an arrow function as default from a page

### ISSUE THREAD

**Issue by hazae41** [alephjs/aleph.js#21]
The default syntax is

```typescript
export default function Home(){
  // ...
}
```

but when I use an arrow function

```typescript
export default () => {
  // ...
}
```

I get a blank page with `400 - Module "undefined" should export a React Component as default`

However, it works when declaring then exporting

```typescript
const Home = () => {
  // ...
}

export default Home
```

or when using `forwardRef`

```typescript
export default forwardRef((props, ref) => {
  // ...
})
```

It would be great if we allowed arrow functions as well as regular functions, what do you think about it?

**Comment by ije** [comment]
sorry, alephjs will check the module's export default ensure it's a validate component:
- must a function component or class component extends React.Component(don't support fast refresh)
- function component must be named with `/^[A-Z]/`

best practice with arrow function is:
```jsx
const Home = () => {
  // ...
}

export default Home
```
