### ISSUE TITLE
v0.3.0-alpha.15 init project  run dev  err

### ISSUE THREAD

**Issue by Lontten** [alephjs/aleph.js#212]
win10
deno 1.8.2 (release, x86_64-pc-windows-msvc)
v8 9.0.257.3
typescript 4.2.2
aleph  v0.3.0-alpha.15

aleph init hello
cd hello
aleph dev

```
error: Uncaught (in promise) TypeError: Cannot set property navigator of #<Window> which has only a getter
        Object.assign(globalThis, {
               ^
    at Function.assign (<anonymous>)
    at Project._init (https://deno.land/x/aleph@v0.2.28/project.ts:600:16)
    at async https://deno.land/x/aleph@v0.2.28/project.ts:106:13
    at async start (https://deno.land/x/aleph@v0.2.28/server.ts:12:5)
```

**Comment by shadowtime2000** [comment]
The templates are not updated to use v0.3.0-alpha versions yet. We will update them when we get to v0.3.0-beta.

**Comment by ije** [comment]
@Lontten template has been updated already for 0.3, i saw the output was using v0.2.28, can you please tell what `aleph -- version` print? thanks 👍

**Comment by Lontten** [comment]
After run upgrade  , it can run normally.
