### ISSUE TITLE
Wrong or Missing exsternal css in production mode

### ISSUE THREAD

**Issue by vincenzopalazzo** [alephjs/aleph.js#217]
I'm running my app in dev mode and I see all the style good, like that

![Screenshot from 2021-03-26 21-18-40](https://user-images.githubusercontent.com/17150045/112688274-e8ed0800-8e78-11eb-9cbf-0cc6f4193a67.png)

But is I mode the app in production mode, I see the following effect

![Screenshot from 2021-03-26 21-19-52](https://user-images.githubusercontent.com/17150045/112688341-06ba6d00-8e79-11eb-80ef-a529dca3f0df.png)

All the CSS from material UI is missed.

Version: alpha18

Sorry if I open a lot of issue but I'm starting with this stuff and I need time before start to contribute

**Comment by ije** [comment]
any message print？

**Comment by vincenzopalazzo** [comment]
During the build phases?

**Comment by ije** [comment]
in Devtools console

**Comment by vincenzopalazzo** [comment]
no any, you can run the app and make all test, in Italy are 2am and I'm going to sleep, sorry 

The app is here https://github.com/clightning4j/ln-sanitycheck

**Comment by AleCandido** [comment]
More or less same problem here:
- both in SSR production and SSG, the style it is not properly managed (while it works wonderfully for `aleph dev`)
- I'm using `styled-components`, but even style rules in standalone sheets seem not to be applied (but they seem to in the example scaffolding `aleph init ...`)
- I also tried to delete `.aleph` like in #130 , nothing changed

**Comment by ije** [comment]
@AleCandido which version you are use?

**Comment by AleCandido** [comment]
```
aleph.js v0.3.0-alpha.33
deno 1.10.1
```
Unfortunately with former versions I was not even able to run `aleph start` and `aleph build`, for some reason it was raising errors (I actually investigated a bit and it looked like it was already solved in the unreleased version, so I've just waited).

**Comment by ije** [comment]
beta version should fixed this since the css loader has been rewrited

**Comment by ije** [comment]
close ref #388
