### ISSUE TITLE
[Bug] cannot compile the template project

### ISSUE THREAD

**Issue by satanya-zero** [alephjs/aleph.js#219]
error: Uncaught (in promise) TypeError: Import 'https://deno.land/x/aleph@v0.3.0-alpha.21/plugins/css.ts' failed: 404 Not Found

**Comment by ije** [comment]
@satanya-zero alpha.21 has removed the css plugin, as instead we support builtin css, please remove the css in your `aleph.config.ts`, i will update the tempalte later, thanks!

**Comment by satanya-zero** [comment]
thank you.
