### ISSUE TITLE
Equivalent of Next.js getServerSideProps in Aleph?

### ISSUE THREAD

**Issue by khromov** [alephjs/aleph.js#22]
I was reading the documentation about the [useDeno](https://alephjs.org/docs/advanced-features/use-deno-hook) hook and it says:

> In Next.js, two functions called getStaticProps and getServerSideProps are used by the pages to fetch data at build time(SSR) or on each request. This solution isolates the data and view likes different roles of the back-end and front-end.

> In Aleph.js, we prefer the mixed solution, a react hook called useDeno provided that allows you fetch data at build time(SSR) in a component with Deno runtime, that's more React Style likely:

After reading the examples, it appears you can only use the `getStaticProps` approach from Next (ie. fetching data at build time), but that there is no way to use the `getServerSideProps` approach?

A common use case for this that I don't understand how to solve in Aleph:

* I have a site that needs to fetch some data locked behind a `Bearer` token. I want to pass this data as the initial props data to the component. I don't want this code in the frontend bundle. 
* I don't plan to hydrate this data on the frontend at all after initial load.

Is this use case not supported in Aleph? If not, it hampers the functionality to unusable levels for our projects. If it is indeed possible, can you please document how to use `useDeno` together with dynamic SSR that can fetch data on each request?

**Comment by ije** [comment]
i'm planning to improve the `useDeno` hook in **v0.3.0**, will support dynamic SSR that can fetch data on each request. 
like you say, currently alphejs will bundle the `useDeno` code even it's *dead-code* in browser, but this can be optimized by the new comilper in **v0.3.0** .

**Comment by mohsenkhanpour** [comment]
It would be good to provide docs for class based components too.
`getStaticProps`, `getServerSideProps` would work in class based components too.
`useDeno` is a great idea, and less confusing than Next.js implementation.

**Comment by ije** [comment]
@mohsenkhanpour i almost forgot how write a class component...but you are definitely right, should provide the `gerStaticProps` and `getServerSideProps` compatibility, and easier to migrate the next app to aleph. thanks 👍

**Comment by alfredosalzillo** [comment]
Something like a withUseDeno hight order component should work.

```javascript
const withUseDeno = (fn) => (Component) => (props) => {
     const ssrProps = useDeno(fn);
     return <Component {...ssrProps} {...props} />
}

class HelloDeno {
   render() {
     const { version } = this.props;
     return <p>Hello i'm Deno v{version}</p>
   }
}

export default withUseDeno(() => ({ version: Deno.version.deno }))(HelloDeno);
```

**Comment by ije** [comment]
hi @alfredosalzillo, I like the *HOC* idea, are you interested in implementing it? or i will add it later, also `withRouter` for `useRouter`, thanks

**Comment by alfredosalzillo** [comment]
I'd like to contribute :)

**Comment by talentlessguy** [comment]
IMO `useDeno` hook doesn't provide the main feature of Next.js `getServerSideProps` - access to `req` object

having it would be great
