### ISSUE TITLE
Why does the import_map file not change my react version in transpiled code?

### ISSUE THREAD

**Issue by aadamsx** [alephjs/aleph.js#223]
I started out on Alpha.12 and moed to Alpha.22.  I wanted to change my react version from 17.0.1 to 17.0.2 so I turned to the import_map.json file that looked like this to start in Alpha.12:

```
{
    "imports": {
        "~/": "./",
        "@/": "./",
        "aleph": "https://deno.land/x/aleph@v0.3.0-alpha.12/mod.ts",
        "aleph/": "https://deno.land/x/aleph@v0.3.0-alpha.12/",
        "react": "https://esm.sh/react@17.0.1",
        "react-dom": "https://esm.sh/react-dom@17.0.1"
    },
    "scopes": {}
}

```

After moving moving to ```alpha.22``` with the following command ```aleph upgrade``` and since Aleph does not change the import map via this upgrade, I manually changed it to the following just targeting the react version (I didn't change the aphla version because it will [throw an error](https://github.com/alephjs/aleph.js/issues/222)):

```
{
    "imports": {
        "~/": "./",
        "@/": "./",
        "aleph": "https://deno.land/x/aleph@v0.3.0-alpha.12/mod.ts",
        "aleph/": "https://deno.land/x/aleph@v0.3.0-alpha.12/",
        "react": "https://esm.sh/react@17.0.2",
        "react-dom": "https://esm.sh/react-dom@17.0.2"
    },
    "scopes": {}
}
```
When doing a ```aleph dev -reload``` and then an ```aleph dev``` I see in the .aleph/development directory that the generated code still references react 17.0.1, why?  And how does the import map actually effect the transpiler?

For example I see this in .aleph/development/app.js, with a reference to react 17.0.1 even though my import map is set to a higer version.

```
var _c;
import __ALEPH_Head from "./-/deno.land/x/aleph@v0.3.0-alpha.22/framework/react/head.js";
import React from "./-/esm.sh/react@17.0.1.js";
import People from "./components/People.js#/components/People.tsx@1818f4";
export default function App({ Page , pageProps  }) {
    return React.createElement("main", {
        __source: {
            fileName: "/app.tsx",
            lineNumber: 6
        }
    }, React.createElement(__ALEPH_Head, {
        __source: {
            fileName: "/app.tsx",
            lineNumber: 7
        }
    }, React.createElement("meta", {
        name: "viewport",
        content: "width=device-width",
        __source: {
            fileName: "/app.tsx",
            lineNumber: 8
        }
    })), React.createElement(People, {
        __source: {
            fileName: "/app.tsx",
            lineNumber: 10
        }
    }), React.createElement(Page, Object.assign({
    }, pageProps, {
        __source: {
            fileName: "/app.tsx",
            lineNumber: 11
        }
    })));
};
_c = App;
$RefreshReg$(_c, "App");
//# sourceMappingURL=app.js.map
```

Code example: https://github.com/aadamsx/aleph-error

**Comment by ije** [comment]
i updated the react version to **17.0.2**, but yes it should follow the import_map, i will improve this later, thanks

**Comment by ije** [comment]
now the compiler will follow the react version in import map, pls try the beta version, thanks
