### ISSUE TITLE
aleph start produces react error 321

### ISSUE THREAD

**Issue by KotlinIsland** [alephjs/aleph.js#229]
```
> aleph start
INFO Compiling...
INFO - bundle
INFO   {} polyfill.js (ES2015) • 9KB
INFO   {} deps.js • 160KB
INFO   {} shared.js • 431B
INFO   {} /pages/index.js • 5KB
INFO   {} main.js • 385B
INFO Server ready on http://localhost:8080/
```
```
500 - Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```
```
> aleph --version
aleph.js 0.3.0-alpha.22
deno 1.8.2
v8 9.0.257.3
typescript 4.2.2
```

**Comment by TranquilMarmot** [comment]
I had to do the following...
- Run `deno install --unstable -A -f -n aleph https://deno.land/x/aleph@v0.3.0-alpha.21/cli.ts` to downgrade to aleph `0.3.0-alpha.21` (it looks like `0.3.0-alpha.22` has breaking changes? https://github.com/alephjs/aleph.js/issues/222)
- Restart my shell to actually pick up the new version
- Start the server with `aleph dev -reload`

However, `0.3.0-alpha.21` does not have CSS support so you will get issues with any styles that you are trying to use.

(P.S. If you start with `aleph dev` you can see the full error!)

**Comment by KotlinIsland** [comment]
`aleph dev` works fine for me. It seems to only be `aleph start` that is affected.

**Comment by TranquilMarmot** [comment]
Interesting... I get that error with both on aleph version `0.3.0-alpha.22`

**Comment by KotlinIsland** [comment]
hmm, I did a reload and now it's working find with `start`.

**Comment by KotlinIsland** [comment]
maybe it was caching different versions of react.

**Comment by KotlinIsland** [comment]
@TranquilMarmot try deleting the .aleph folder and reloading everything, deno might be using a cached old version of something.
