### ISSUE TITLE
Fix Discord invite link

### ISSUE THREAD

**Issue by mohsenkhanpour** [alephjs/aleph.js#23]
Thanks for creating the Discord server, I saw the README.MD update with the link.

However the link you have used is for a channel inside the server, so if someone is not part of server and they click on it, they cannot see channel.

You should create an invite link and set expire date to never so you can use it as a permalink to invite members. In order to do so:
1. Click on "Create Invite" icon:
![image](https://user-images.githubusercontent.com/28626829/98538407-f629a180-229f-11eb-8590-8667df6b1a7c.png)

2. Click on "edit invite link":
![image](https://user-images.githubusercontent.com/28626829/98538519-1f4a3200-22a0-11eb-944c-476b54284065.png)

3. Don't use limits and expiration date so you won't have to update the link again
![image](https://user-images.githubusercontent.com/28626829/98538596-3be66a00-22a0-11eb-8fb6-44e706a8d9dd.png)

4. Generate invite and update the link in README.MD:
![image](https://user-images.githubusercontent.com/28626829/98538665-5c162900-22a0-11eb-8d60-f3975b49c9f6.png)

It's something like: https://discord.gg/{inviteCode}

**Comment by ije** [comment]
oh, i'm sorry, will update it later, thank you so much!

**Comment by ije** [comment]
updated, https://discord.gg/pWGdS7sAqD
