### ISSUE TITLE
Add a shutdown method to Server / Application

### ISSUE THREAD

**Issue by KotlinIsland** [alephjs/aleph.js#233]
When using aleph as a middleware on Oak I need to be able to gracefully shutdown the server, could you please provide shutdown methods for this scenario.

**Comment by vincenzopalazzo** [comment]
An good first issue?

**Comment by ije** [comment]
the server accept a signal object to stop the server, pls check https://github.com/alephjs/aleph.js/blob/374c93933c7b992466f0472995707c5e95eb77f6/server/server.ts#L304
