### ISSUE TITLE
useEffect React Hook not working

### ISSUE THREAD

**Issue by imjwang** [alephjs/aleph.js#239]

**Comment by imjwang** [comment]
This increments correctly in Nextjs, but it's not working for me in Alephjs. What can I do about this?

```jsx
import React, { useState } from 'react'

export default function Home() {
  const [count, setCount] = useState(0)
  return (
    <div>
    <h1>You've clicked {count} Times!</h1>
    <a className="button" onClick={() => setCount(count+1)}>
    Search
    </a>
    </div>
  )
}
```

**Comment by shadowtime2000** [comment]
@imjwang Can you provide more details like reproduction, Deno OS and Aleph version?

**Comment by hazae41** [comment]
Try importing React from esm.sh

**Comment by imjwang** [comment]
importing from esm.sh did not work for me

**Comment by shadowtime2000** [comment]
@imjwang The template uses import maps. You should check out the docs on using them then.
