### ISSUE TITLE
Add support for exposing environment variables to the browser

### ISSUE THREAD

**Issue by noverby** [alephjs/aleph.js#240]
In Next.js environment variables prefixed with `NEXT_PUBLIC_` are exposed to the browser.
It would be neat if aleph.js provided something similar.

**Comment by vincenzopalazzo** [comment]
+1

**Comment by ije** [comment]
i think `const value = useDeno(() => Deno.env.get('key'))` is a better way to get sys environment.

**Comment by shadowtime2000** [comment]
These was talk about creating an SWC macros system #78, you can just use what @ije pointed out macros once they are released.

**Comment by ije** [comment]
@shadowtime2000 i almost forgot that conversation, too many things need to be done...but yes we will implement the macro feature!
