### ISSUE TITLE
please provide an example of aleph + rust

### ISSUE THREAD

**Issue by bionicles** [alephjs/aleph.js#244]
How would one route to Aleph from a rust API server using something like actix-web, tide, warp, rocket etc? 

This would make an extremely solid option for Rust projects to do front end, because we could avoid having to deploy the front end and the rust api separately (and route to them, load balancing, dns etc etc)

**Comment by shadowtime2000** [comment]
@bionicles afaik this is isn't even possible with our current system, and I don't see it as something that is really necessary for the near future.

**Comment by ije** [comment]
@bionicles alephjs is a javascript (typescript) framework in deno, rust is not in the context.

**Comment by ije** [comment]
@bionicles try yew!
