### ISSUE TITLE
ERROR Fetch modules when with hello project

### ISSUE THREAD

**Issue by deathemperor** [alephjs/aleph.js#245]
First of all: thank you for your great works! I'm super excited with Deno and will be following its growth along with projects like these. I've just started my first experiment on Deno with aleph. Got this error trying to run `aleph dev` on 0.3.0 alpha 24

```
aleph --version
aleph.js 0.3.0-alpha.24
deno 1.8.2
v8 9.0.257.3
typescript 4.2.2
```

The logs

```
aleph dev
[ "autoprefixer" ]
INFO Compiling...
ERROR Fetch module '/react': No such file
ERROR Fetch module '/pages/framework/react': No such file
ERROR Fetch module '/pages/react': No such file
ERROR Fetch module '/pages/~/components/logo.tsx': No such file
ERROR Fetch module '/pages/~/lib/useCounter.ts': No such file
INFO Start watching code changes...
INFO Server ready on http://localhost:8080/
```

I also get these VSCode errors, any hint for fixing? I couldn’t find any solutions googling.

![vscode](https://user-images.githubusercontent.com/4255482/113431277-b48fc380-9405-11eb-8564-15a18ed876a1.png)

**Comment by ije** [comment]
does the import maps exist?

**Comment by deathemperor** [comment]
> does the import maps exist?

No config in export maps

**Comment by shadowtime2000** [comment]
@deathemperor Were you using the template that comes with `aleph init`?

**Comment by deathemperor** [comment]
> @deathemperor Were you using the template that comes with `aleph init`?

I dont think so. I followed the Getting Started guide here: https://alephjs.org/docs/get-started.


hmm. I've just started everything from scratch while writing this and it works. I believe the error was because I created the project with aleph@v0.2.28, ran with errors then upgrade aleph to latest (0.3.0 alpha 24) => run yarn dev and got this issue. Think you may wanna update the https://alephjs.org/docs/get-started page.

Thanks again. Closing issue.

**Comment by shadowtime2000** [comment]
@deathemperor We are going to update the website docs once we are able to actually use 0.3.0-alpha for the website.
