### ISSUE TITLE
The default value of query returned from useRouter() is undefined

### ISSUE THREAD

**Issue by noverby** [alephjs/aleph.js#246]
The default value of query returned from useRouter() is `undefined`.
In the Next.js router the default value of query is `{}`.

**Comment by noverby** [comment]
Example where it results in an uncaught exception.

## Stacktrace
```
Uncaught TypeError: currentQuery is undefined
    currentHref anchor.ts:44
    React 3
    Anchor anchor.ts:43
    React 17
    bootstrap bootstrap.ts:48
anchor.ts:44:29
    currentHref anchor.ts:44
    React 3
    Anchor anchor.ts:43
    React 17
    bootstrap bootstrap.ts:48
    AsyncFunctionNext self-hosted:690
```

##  https://deno.land/x/aleph@v0.3.0-alpha.22/framework/react/anchor.ts:44
```
const { pathname: currentPathname, query: currentQuery } = useRouter()
  const currentHref = useMemo(() => {
    return [currentPathname, currentQuery.toString()].filter(Boolean).join('?')
```

**Comment by ije** [comment]
up to alpha.24 that fixed this, but there is a breaking change, i combined `params` and `query` to `params` as a   `URLSearchParams` object

**Comment by noverby** [comment]
Yes the problem is solved with alpha.24
