### ISSUE TITLE
Cannot resolve module 'head' error when importing Tailwind

### ISSUE THREAD

**Issue by khromov** [alephjs/aleph.js#25]
I'm trying to [add Tailwind](https://alephjs.org/docs/basic-features/built-in-css-support) to `app.tsx`:

`app.tsx`

```
import "https://unpkg.com/tailwindcss@1.9.1/dist/tailwind.min.css"
```

but I'm getting:

```
ERROR TypeError: Cannot resolve module "file:///home/k/-/deno.land/x/aleph/head.js" from "file:///home/k/GitHub/aleph-operator-lookup/.aleph/development.es2018/-/unpkg.com/tailwindcss@1.9.0/dist/tailwind.css.js".
    at file:///home/k/GitHub/aleph-operator-lookup/.aleph/development.es2018/-/unpkg.com/tailwindcss@1.9.0/dist/tailwind.css.js:1:0
WARN page '/-/deno.land/x/aleph/head.js' not found
```

**Comment by buttercubz** [comment]
@khromov import css in `style/index.less`

**Comment by khromov** [comment]
@buttercubz Thanks, it works as a workaround, but I was under the impression that with module import you could have it bundled with your JS (which is what I want), not as an external dependency.

**Comment by shadowtime2000** [comment]
@khromov I believe that bundling was on the `v0.3.0` roadmap (#5) so you may be able to do something like that after.

**Comment by ije** [comment]
i think this is a bug, i will figure it out. and i'm considering a pugin for tailwind to support **tree-sharking**.

**Comment by shadowtime2000** [comment]
@ije How exactly would that work? Something like CSS modules?

**Comment by ije** [comment]
@shadowtime2000 maybe use postcss plugin: https://tailwindcss.com/docs/installation#process-your-css-with-tailwind

**Comment by ije** [comment]
fixed
