### ISSUE TITLE
import not found: elementType utils.development.js

### ISSUE THREAD

**Issue by noverby** [alephjs/aleph.js#255]
Version: `aleph@v0.3.0-alpha.25`
I don't know if this is a regression. 
If not, then the error message should be clearer about the underlying issue.
```
Uncaught (in promise) SyntaxError: import not found: elementType utils.development.js:92:9
    bootstrap bootstrap.ts:52
    AsyncFunctionThrow self-hosted:694
    (Async: async)
    <anonymous> main.js:3
    InnerModuleEvaluation self-hosted:2379
    evaluation self-hosted:2330
```

**Comment by ije** [comment]
more details?

**Comment by shadowtime2000** [comment]
Given that more information wasn't provided like Deno version and stuff, I am going to close this. Feel free to respond on this issue with more information and I will reopen it.
