### ISSUE TITLE
Default aleph init project does not run

### ISSUE THREAD

**Issue by noverby** [alephjs/aleph.js#256]
Version: `aleph@v0.3.0-alpha.25`
Running `aleph init && aleph dev` results in the following error and a 404 page:
```
Uncaught (in promise) ReferenceError: Deno is not defined
    parseFile mod.ts:78
    config mod.ts:48
    <anonymous> app.js:6
```

**Comment by ije** [comment]
sorry, i can't repeat this, try to clear the cache?

**Comment by KotlinIsland** [comment]
I can reproduce this. I think you are running aleph from outside the project folder.
try running `aleph init hello && aleph dev hello`

**Comment by noverby** [comment]
@KotlinIsland  Whoops my mistake you are correct. A warming could be useful, though.
At least people can look up this issue now, if they get the error.
