### ISSUE TITLE
useDeno hook doesn't track querystring parameter dependencies

### ISSUE THREAD

**Issue by stereosteve** [alephjs/aleph.js#262]
I was using data from the query parameters to fetch data inside of a useDeno hook... but it seems there's no dependency tracking for query params.  

Looking here it uses only the pathname:
https://github.com/alephjs/aleph.js/blob/master/framework/react/hooks.ts#L40

I think it would make sense to use the full URL instead.
(the use case is something like search + pagination /search?q=hello&from=10&limit=20)

**Comment by ije** [comment]
fixed the `dataUrl` to full URL in **alpha.28**, thanks @stereosteve

**Comment by stereosteve** [comment]
Nice... along with [this commit](https://github.com/alephjs/aleph.js/commit/c19f1518af20b3dc5cb40b98924a9d768faf58c2) looks all fixed in alpha.29.  Thanks!

**Comment by stereosteve** [comment]
I thought issue was resolved but there's still some issues with useDeno with querystring:

All of the `/_aleph/data` urls in `pagedata.ts` and `server.ts` still assume `pathname`
So fetching data from `/_aleph/data/*.json` during client side navigation doesn't work and I have to reload page, at least in dev.

I think eventually it'll make sense to fully support SSR with query params, but admit it's probably not a top priority.
For now I'm thinking to use SWR + api routes to bypass SSR, or do something clever to add params to the path like `/q--hello/start--10`.

**Comment by ije** [comment]
@stereosteve yes you are right, currently `/_aleph/data/*.json` does not include the query params and the ssr data request also need to add the query. i will fix this ASAP. thanks!
