### ISSUE TITLE
Support for using arrow functions for React Components

### ISSUE THREAD

**Issue by noverby** [alephjs/aleph.js#269]
The following code does not run:
```typescript
import React from "react";
import { Button } from "https://esm.sh/@material-ui/core";

export default () => {
  return <Button>Test</Button>;
};
```

It results in the error:
```
400 - Module "Page Component: /pages/index.tsx" should export a React Component as default
```

**Comment by shadowtime2000** [comment]
Currently our function to detect if a function is a React component doesn't support arrow functions. @ije Do you know any way it could be done?

**Comment by noverby** [comment]
Next.js uses `isValidElementType` from `react-is` to verify whether the objects, returned from either type of functions, are React components. [Source](https://github.com/vercel/next.js/blob/0af3b526408bae26d6b3f8cab75c4229998bf7cb/packages/next/next-server/server/render.tsx#L503)

**Comment by ije** [comment]
i don't think so `react-is` can get this, in fact the [isLikelyReactComponent](https://github.com/alephjs/aleph.js/blob/e99b54546b334220fd20243655bc3ed0439e0001/framework/react/helper.ts#L7) function is copied from react repo, and the unnamed arrow function component also don't support fast-refresh. try to use `const` snytax:
```jsx
const A = () =><Button>Test</Button>
export default A
```
```

**Comment by noverby** [comment]
@ije Next.js automatically transforms unnamed and arrow functions to have a name for fast-refresh support:
https://github.com/vercel/next.js/blob/canary/packages/next-codemod/transforms/name-default-component.ts

**Comment by ije** [comment]
this should be handle in compiler
