### ISSUE TITLE
The value of the src attribute in the script tag does not compile correctly

### ISSUE THREAD

**Issue by hyakt** [alephjs/aleph.js#271]
The following script tag 
```tsx
<script src="https://cdn.google.com/ga.js"></script>
```
compile to
```js
<script src="/https:/cdn.google.com/ga.js"></script>
```

$ aleph --version
aleph.js 0.3.0-alpha.29
deno 1.8.3
v8 9.0.257.3
typescript 4.2.2

**Comment by ije** [comment]
@hyakt thanks, i will look into it!

**Comment by ije** [comment]
@hyakt  fixed, please upgrade to **alpha.31**, thanks

**Comment by hyakt** [comment]
Thank you! It's working as expected.
