### ISSUE TITLE
Infinite download loop on start / build

### ISSUE THREAD

**Issue by Gleb-ko** [alephjs/aleph.js#278]
When importing a module within which certain files indirectly import themselves, Deno can handle the import fine; however, `aleph start` or `aleph build` goes into an infinite download loop of these files.

This is the import that is breaking Aleph for me:
```typescript
import { api } from "https://gitlab.com/silk-matrix/matrix.ts/-/raw/0.1.6/mod.ts";
```

Edit 1: I did some searching through the Aleph code, this is the line of the log that indicates that there is an infinite download loop:
https://github.com/alephjs/aleph.js/blob/v0.3.0-alpha.29/server/app.ts#L924

Edit 2: After some more digging I found where the function is that infinitely calls itself at this point:
https://github.com/alephjs/aleph.js/blob/v0.3.0-alpha.29/bundler/mod.ts#L171

**Comment by ije** [comment]
please upgrade to **alaph.30** that fixed this
