### ISSUE TITLE
Production breaks on importing entire module

### ISSUE THREAD

**Issue by Gleb-ko** [alephjs/aleph.js#280]
I am trying to import an entire module which has submodules.
When using `aleph build` or `aleph start` I get this error in the browser console:
```
Uncaught (in promise) TypeError: Cannot destructure property 'default' of '(intermediate value)' as it is undefined.
    at deps.bundle.5a8741c5.js:1
    at Generator.next (<anonymous>)
    at e (deps.bundle.5a8741c5.js:1)
    at i (deps.bundle.5a8741c5.js:1)
````

When using `aleph dev` the code works as intended.

---------

### Example

The import is here (specifically the `api` part):
https://gitlab.com/silk-matrix/silk-desktop/-/blob/aleph-issue-280/src/lib/useLogin.ts#L2

Using this code below has the same effect.
```ts
import * as api from "https://x.nest.land/matrix.ts@0.1.9/src/api/mod.ts";
```

**Comment by ije** [comment]
seems it's swc bundler issue like denoland/deno#9849, i am rewriting the bundler system using esbuild instead, that should work fine.
https://github.com/alephjs/aleph.js/pull/277

**Comment by Gleb-ko** [comment]
@ije I just tried using the master branch into which you have merged #277 and I am afraid I still get the same issue as well as a new error:
```
Uncaught TypeError: Cannot destructure property 'join' of '__ALEPH.pack.https://deno.land/std@0.85.0/path/mod.ts' as it is undefined.
    at login.bundle.009969a3.js:1
    at login.bundle.009969a3.js:43
```

**Comment by ije** [comment]
deno 1.9？

**Comment by Gleb-ko** [comment]
Yes

**Comment by ije** [comment]
<img width="1187" alt="Screen Shot 2021-04-17 at 5 06 00 PM" src="https://user-images.githubusercontent.com/2883484/115107743-60591780-9f9f-11eb-9772-50191d87e5f0.png">

fixed.

**Comment by ije** [comment]
alpha.30 can work fine in your example on macos

**Comment by Gleb-ko** [comment]
aleph.30 does fix it, not sure why it didn't work from the master branch yesterday
