### ISSUE TITLE
redirect doesn't work

### ISSUE THREAD

**Issue by Gleb-ko** [alephjs/aleph.js#283]
Using redirect doesn't work in alpha 30, for example:

```tsx
import React, { useEffect } from "react";
import { redirect } from "framework";

export default function Page() {
    useEffect(() => {
        redirect("/somepage");
    }, []);
    return <p> Should not be seen because redirected </p>;
}
```

**Comment by ije** [comment]
does the url change in address bar?

**Comment by Gleb-ko** [comment]
yes it does

**Comment by ije** [comment]
try to set a timeout out of the redirect call, since the router event listener is not ready

**Comment by ije** [comment]
if you want to rewrited page url, try to set rewriting rules in `aleph.config.ts` instead

**Comment by Gleb-ko** [comment]
> try to set a timeout out of the redirect call, since the router event listener is not ready

this doesn't work. I should mention that if I reload on that page the redirect works properly.

**Comment by Gleb-ko** [comment]
> if you want to rewrited page url, try to set rewriting rules in `aleph.config.ts` instead

I have some logic behind whether it would redirect or not (so the page doesn't necessarily redirect), so I can't do it with a static rule.

**Comment by ije** [comment]
@Gleb-ko fixed, please upgrade to **alpha.31** and try again, thanks

**Comment by Gleb-ko** [comment]
@ije I'm afraid the above example still does not work for me
