### ISSUE TITLE
Property 'value' does not exist on type 'HTMLInputElement'.

### ISSUE THREAD

**Issue by tzx** [alephjs/aleph.js#287]
I don't know if this is an issue on my end, but I am doing a simple onChange for an input and I get the error in the title which doesn't make sense I think.

```
  const [poolName, setPoolName] = useState("");

  const onChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setPoolName((e.target as HTMLInputElement).value)
  };
```
I am using v0.3.0 alpha 31

**Comment by ije** [comment]
because deno doesn't provide the dom types as default, you can add it like:

```ts
/// <refenerce lib="dom">
```

or declear it in `tsconfig.json`.
