### ISSUE TITLE
srcDir ignored for the public directory

### ISSUE THREAD

**Issue by Gleb-ko** [alephjs/aleph.js#291]
If you set the `srcDir` option in `aleph.config.js` the `public` directory is taken from `"./"` instead of the `srcDir`

**Comment by jheysonsaav** [comment]
generally the public and src folders are used separately, and so it is used by projects like create-react-app or vue-cli, maybe that's why the behavior of alephjs is to wait for the public directory in the same path as the src directory

**Comment by Gleb-ko** [comment]
@jheysonsaav ah ok, that would make sense. Not too familiar with React but after looking at example projects & `create-react-app` I think that is probably the case so I'll close this issue.
