### ISSUE TITLE
Crash / infinite loop on remote self-import

### ISSUE THREAD

**Issue by cyclane** [alephjs/aleph.js#294]
`aleph dev` crashes with no error message on a remote self-import and `aleph start` or `aleph build` enters an infinite loop.

This is not an issue last on alpha.30 but broken for both alpha.31 and alpha.32

Replication:
Put this line in `app.tsx`
```ts
import "https://x.nest.land/matrix.ts@0.1.10/mod.ts";
```

Edit:
Made a much shorter remote module for replication:
```ts
import "https://gitlab.com/Glebko/test/-/raw/master/test1.ts";
```

(similar to #285 but the example there does work)

**Comment by ije** [comment]
@Gleb-ko thanks for the details, i will check out later!

**Comment by ije** [comment]
i guss this has been fixed in beta branch
