### ISSUE TITLE
Social media meta tags not included in index.html

### ISSUE THREAD

**Issue by hsjoberg** [alephjs/aleph.js#297]
Hello, thank you for a great project!

I have some issues regarding meta tags (and other tags for that matter). AFAICT the recommended method is by adding a `<head>` section to a rendered component, and Aleph will take of adding this to the real `<head>` section.

This introduces issues with social media meta-tags however, like those used for Twitter and Facebook, as they require them to be accessible directly when retrieving index.html.

Any ideas on how to solve this one? Perhaps the index.html should be editable, like with create-react-app, webpack and others.

Cheers!

**Comment by shadowtime2000** [comment]
> This introduces issues with social media meta-tags however, like those used for Twitter and Facebook, as they require them to be accessible directly when retrieving index.html.

What do you mean by this?

**Comment by hsjoberg** [comment]
@shadowtime2000 I don't believe they are executing Javascript, so the meta-tags are never added to `<head>` read.

When I build a production version and check index.html, the tags are not there. But when I then visit my page, they are added, so I assume this was done afterwards by Javascript.

**Comment by shadowtime2000** [comment]
@hsjoberg I am fairly sure that we statically add the meta tags and they are added in the SSG process, what you are experiencing might be a bug.

**Comment by hsjoberg** [comment]
@shadowtime2000 I see.
If it helps I am running with SSR disabled.

I can also put up an exampe repository when I got time.

**Comment by shadowtime2000** [comment]
> If it helps I am running with SSR disabled.

Idk why you are expecting meta tags to be SSRed when you have SSR disabled. 

I don't think having an `index.html` is really necessary because SPAs are not built to like be great for SEO, if you want good SEO with meta tags you should use SSR/SSG instead.

**Comment by hsjoberg** [comment]
@shadowtime2000 The purpose of the social media tags in this context are not for SEO, it is for sharing  on social media sites, where an image, description and other content from the tags will be read and displayed.

> Idk why you are expecting meta tags to be SSRed when you have SSR disabled.

Yeah sorry, I was a bit confused about how Aleph.js worked here. But yes this makes full sense now.
This is also why I asked that perhaps the index.html could be editable like with webpack.
