### ISSUE TITLE
404 error on new project

### ISSUE THREAD

**Issue by hazae41** [alephjs/aleph.js#298]
Hey, I just started a new Aleph project, but I get a 404 error

> $ aleph init
> $ aleph dev

> open http://localhost:8080/

![Capture](https://user-images.githubusercontent.com/4405263/117275947-da721300-ae5e-11eb-8090-84b43a9e20ae.PNG)

How can I get the main page?

**Comment by hazae41** [comment]
I just restarted the project with `aleph dev` and now it works

**Comment by hazae41** [comment]
I made yet another new project and it works too, weird

**Comment by MarkBennett** [comment]
I saw this after following the getting started and running `aleph init`. It turns out I forgot to change into the directory that `aleph init` created. Once I did that the 404 went away and it worked as expected.

Is it possible this is what happened for you as well @hazae41?

**Comment by hazae41** [comment]
idk
