### ISSUE TITLE
not work in legend Edge 

### ISSUE THREAD

**Issue by ije** [alephjs/aleph.js#3]
The browser can load modules but not render pages.

**Microsoft Edge 42.17134.1.0**
Microsoft EdgeHTML 17.17134

**Comment by shadowtime2000** [comment]
Maybe I am not fully understanding the problem here but this could get fixed with bundling (#8)?

**Comment by ije** [comment]
bundling shall fix this, but dev mode still has this issue

**Comment by shadowtime2000** [comment]
@ije I think it is safe to assume that developers would use modern browsers which support ES modules. That should probably be written that as a note in the docs.

**Comment by ije** [comment]
that is make sense
