### ISSUE TITLE
Do not process .css files in public/ folder

### ISSUE THREAD

**Issue by hazae41** [alephjs/aleph.js#304]
I tried to include [tailwind.min.css](https://esm.sh/tailwindcss/dist/tailwind.min.css), which is very big, in my public/ folder directly instead of using its url

However, `aleph build` hangs when building that file

It would be cool if we could ignore some files from the processing, either manually or when the file is named ".min.css"

**Comment by ije** [comment]
yes, the CSS loader should ignore CSS files in public dir, i will improve this!

**Comment by hazae41** [comment]
It also hangs when using

```typescript
<link rel="stylesheet" href="https://esm.sh/tailwindcss/dist/tailwind.min.css" />
```

in app.tsx
