### ISSUE TITLE
Lack of URL encoding processing

### ISSUE THREAD

**Issue by masataka** [alephjs/aleph.js#31]
Due to the lack of URL encoding processing, requesting a URL with spaces / unicode strings / more for the pages / APIs / static files will result in a 404 error.

#### File structure
- "public"
     - "a b"  <- with space!
        - "c.txt"

#### Request
```
https://localhost:8080/a b/c.txt
// Almost all web browsers encode this to "http://localhost:8080/a%20b/c.txt"
```

-> 404 - Page Not Found

**Comment by ije** [comment]
i will figure it out, thanks @masataka

**Comment by masataka** [comment]
@ije Thanks a lot! your project excited me.
(I saw /alephjs/aleph.js/blob/master/server.ts.) And...I think static files should be resolved faster than page services and API services. This is because pages and APIs are dynamically routeable and can unintentionally handle requests for static files.
Since the API is placed in a special api path, it would be better to solve it in the order of 1) static file, 2) API, 3) page.
Sorry, I don't know this order of NEXT.js.

**Comment by ije** [comment]
@masataka  glad you like Aleph.js and thanks for your issues to make the framework better.

i think should put APIs routes before static files, **for example**, you want to render images using api then you should ensure the `/api/*.jpg` does not exist in the `public` folder if you change the order to static file as first:
 
- /api/avatar.jpg.ts
- /public/api/avatar.jpg (conflict)

**Comment by ije** [comment]
but we can improve the routing prefs in the future.

**Comment by masataka** [comment]
@ije I think static files are very intentionally placed because of static one. It's a very special and intentional case If you create an api folder directly under /public. But in the future, the dynamic routing specification is extended to do the following, that special case would be useful as well.

- /api/avatar[ID].jpg.ts <- an extended specification (I dream), doesn't work today.
- /public/api/avatar404.jpg <- this is fallback of illegal ID.
