### ISSUE TITLE
Aleph.js needs Deno 1.8.0+, please upgrade Deno

### ISSUE THREAD

**Issue by golamrabbiazad** [alephjs/aleph.js#312]
Getting error message after hit `aleph dev`.

> ERROR Aleph.js needs Deno 1.8.0+, please upgrade Deno.

Version info:-

```applescript
aleph.js 0.3.0-alpha.32
deno 1.10.1
v8 9.1.269.27
typescript 4.2.2
```

**Comment by shadowtime2000** [comment]
Can you supply full reproduction steps?

**Comment by hazae41** [comment]
I have the same thing when building with Deno 1.10

**Comment by hazae41** [comment]
This is basically because Aleph has

```typescript
if (Deno.version.deno < minDenoVersion) {
  log.error(`Aleph.js needs Deno ${minDenoVersion}+, please upgrade Deno.`)
  Deno.exit(1)
}
```

and `minDenoVersion = '1.8.0'`

But it is true when using 1.10+

```
> "1.9.2" < '1.8.0'
false
> "1.10.1" < '1.8.0'
true
```

**Comment by kamchy** [comment]
Hi, I stumbled upon this issue today and I propose to use existing solution - [compare-versions](https://deno.land/x/compare_versions@0.4.0 ) - to handle this.

**Comment by alundiak** [comment]
I do confirm, that this error disappeared. Thanks.
