### ISSUE TITLE
alephjs.org getstard need update

### ISSUE THREAD

**Issue by elycheikhsmail** [alephjs/aleph.js#315]
instruction for getting start say 
Prerequisites
Deno 1.6.3 
but now deno version is 1.10.1 and aleph version is greet than 0.2.28

**Comment by hazae41** [comment]
Aleph 0.3 is still in alpha that's why

**Comment by shadowtime2000** [comment]
Yes, as @hazae41 Aleph 0.3.0 which is built to work with more modern versions of Deno is in beta and so we are currently keeping the getting started instructions to have instructions for 0.2.28 because that is more stable.
