### ISSUE TITLE
ERROR Aleph.js needs Deno 1.8.0+, please upgrade Deno 

### ISSUE THREAD

**Issue by elycheikhsmail** [alephjs/aleph.js#316]
I get this message
ERROR Aleph.js needs Deno 1.8.0+, please upgrade Deno 
 when running
aleph dev
but I have deno 1.10.1 installed

**Comment by elycheikhsmail** [comment]
when I make searche in aleph repo I found "please upgrade Deno"  in one file in server/app.ts line 109, after if (semver.lt(Deno.version.deno, minDenoVersion)) { it may a bug in https://deno.land/x/semver@v1.3.0

**Comment by hazae41** [comment]
The patch is not release yet

**Comment by elycheikhsmail** [comment]
> The patch is not release yet

 you can give more explication ?

**Comment by elycheikhsmail** [comment]
> The patch is not release yet

I install deno v1.9.0 behind v1.10.1 using dvm and ERROR goes.

**Comment by guidorice** [comment]
I also got this error using deno 1.10.1.

**Comment by guidorice** [comment]
Oh  it was resolved here https://github.com/alephjs/aleph.js/issues/312 👍🏽

**Comment by elycheikhsmail** [comment]
> Oh it was resolved here #312 👍🏽

I think I think there, may other commit broke it again.

**Comment by shadowtime2000** [comment]
This is a duplicate issue which has already been resolved on master, the fix will be present in the next release.
