### ISSUE TITLE
A way to get a JSON from a request body

### ISSUE THREAD

**Issue by shinspiegel** [alephjs/aleph.js#33]
Hi,

There is a way to get a JSON from a request body?

If not, can I help to improve this project providing a function for this?
Maybe creating a new method in the Request class?

Thanks in advance!

**Comment by ije** [comment]
hi @shinspiegel , of course you are welcome to imporve the `Request` class, what the method name you perfer? is it `jsonBody`?
FYI please ref https://deno.land/std@0.77.0/http/server.ts#L56

**Comment by shinspiegel** [comment]
I created a [pull/request](https://github.com/alephjs/aleph.js/pull/35) with the changed, want to discuss [there](https://github.com/alephjs/aleph.js/pull/35) or here?
