### ISSUE TITLE
esm.sh imported component failing

### ISSUE THREAD

**Issue by kratoon3** [alephjs/aleph.js#330]
Hi, thanks for awesome framework!

I am trying to load an existing React component library using esm.sh. 
Not sure if this is esm.sh or esbuild or alephjs issues. 

```js
import React from 'react';
import Button from 'https://esm.sh/@salesforce/design-system-react/components/button';

export default function Test() {
    return (<Button label="Neutral" />);
}
```

```
Error: cb is not a function
TypeError: cb is not a function
    at file:///Users/project/.aleph/development/-/cdn.esm.sh/v41/react-required-if@1.0.3/deno/react-required-if.development.js:11:41
    at file:///Users/project/.aleph/development/-/cdn.esm.sh/v41/react-required-if@1.0.3/deno/react-required-if.development.js:55:43
```

The js file is [here on pastebin](https://pastebin.com/iwUAN5UH)

aleph.js 0.3.0-alpha.33
deno 1.10.2
v8 9.1.269.27
typescript 4.2.2
react 17.0.2

**Comment by FallingSnow** [comment]
Did you try another cdn, such as skypack.dev?

**Comment by kratoon3** [comment]
@FallingSnow skypack.dev is working great. Thanks!
