### ISSUE TITLE
Routing with [param].tsx doesn't work

### ISSUE THREAD

**Issue by talentlessguy** [alephjs/aleph.js#331]
every page I create has these parameters, no matter if it's a folder, or a file with params.

I tried moving this file to `[coin]/[address].tsx`, to `test/[address].tsx`  and `[address].tsx` but it's all the same:

```tsx
import { balance } from 'https://deno.land/x/balance_crypto@0.2.11/deno/mod.ts'
import { useRouter, useDeno } from 'https://deno.land/x/aleph@v0.3.0-alpha.8/framework/react/hooks.ts'
import React, { useState } from 'react'

export default function Home(props) {
  const { params, pagePath, query } = useRouter()

  const { address, coin } = params

  console.log(params, query.get('coin'), pagePath, props)

  if (!address) return <h1>Missing address</h1>
  if (!coin) return <h1>Missing token symbol</h1>

  const [data, set] = useState<{ asset: string; balance: number }>()

  useDeno(async () => {
    await balance(address, coin, {
      apiKeys: {},
      verbose: true
    }).then((d) => set(d))
  })

  console.log(data)

  return <h1>test</h1>
}
```

yields this:

```
INFO modify /pages/[address].tsx
{} null / {}
INFO render '/eth' in 56ms
```

it doesn't happen with `test.tsx` though (it maps to `/test` properly)

```
➜ aleph --version
aleph.js 0.3.0-alpha.33
deno 1.10.2
v8 9.1.269.27
typescript 4.2.2
```

**Comment by thomascarvalho** [comment]
Your import version doesn't match.
Replace your import by `import { useRouter, useDeno } from 'https://deno.land/x/aleph@v0.3.0-alpha.33/framework/react/hooks.ts'`

I don't know in which version it was corrected but with alpha.33 it works

**Comment by thomascarvalho** [comment]
I advise you to use an import_map.json to make sure you have the same version everywhere.

**Comment by talentlessguy** [comment]
my bad, i didn't see that the import URL has an old version
