### ISSUE TITLE
ERROR Load module 'https://deno.land/x/aleph@v0.3.0-alpha.33/mod.ts': Not Found

### ISSUE THREAD

**Issue by asbjornu** [alephjs/aleph.js#333]
Importing `useRouter` from [the example](https://alephjs.org/docs/basic-features/routing) just gives me the following exception when executing `aleph dev`:

```
INFO Download https://deno.land/x/aleph@v0.3.0-alpha.33/mod.ts
WARN Download https://deno.land/x/aleph@v0.3.0-alpha.33/mod.ts failed, retrying...
WARN Download https://deno.land/x/aleph@v0.3.0-alpha.33/mod.ts failed, retrying...
WARN Download https://deno.land/x/aleph@v0.3.0-alpha.33/mod.ts failed, retrying...
WARN Download https://deno.land/x/aleph@v0.3.0-alpha.33/mod.ts failed, retrying...
WARN Download https://deno.land/x/aleph@v0.3.0-alpha.33/mod.ts failed, retrying...
WARN Download https://deno.land/x/aleph@v0.3.0-alpha.33/mod.ts failed, retrying...
WARN Download https://deno.land/x/aleph@v0.3.0-alpha.33/mod.ts failed, retrying...
WARN Download https://deno.land/x/aleph@v0.3.0-alpha.33/mod.ts failed, retrying...
WARN Download https://deno.land/x/aleph@v0.3.0-alpha.33/mod.ts failed, retrying...
ERROR Load module 'https://deno.land/x/aleph@v0.3.0-alpha.33/mod.ts': Not Found
error: Uncaught (in promise) Error: Not Found
        err = new Error(resp.statusText)
              ^
    at cache (https://deno.land/x/aleph@v0.3.0-alpha.33/server/cache.ts:51:15)
    at async Application.fetch (https://deno.land/x/aleph@v0.3.0-alpha.33/server/app.ts:830:12)
    at async Application.loadModule (https://deno.land/x/aleph@v0.3.0-alpha.33/server/app.ts:886:22)
    at async Application.initModule (https://deno.land/x/aleph@v0.3.0-alpha.33/server/app.ts:1021:51)
    at async https://deno.land/x/aleph@v0.3.0-alpha.33/server/app.ts:1169:27
    at async Promise.all (index 5)
    at async Application.transpileModule (https://deno.land/x/aleph@v0.3.0-alpha.33/server/app.ts:1167:7)
    at async https://deno.land/x/aleph@v0.3.0-alpha.33/server/app.ts:1171:11
    at async Promise.all (index 4)
    at async Application.transpileModule (https://deno.land/x/aleph@v0.3.0-alpha.33/server/app.ts:1167:7)
```

I assume the example is for an older version of Aleph? When changing from:

```javascript
import { useRouter } from "https://deno.land/x/aleph/mod.ts"
```

to:

```javascript
import { useRouter } from 'framework/react'
```

…it stops complaining, but my deconstructed `pathname`, `pagePath`, `params` and `query` variables come up empty. 

What I want is as mundane as **retrieving the currently requested URL** (particularly the query string). How can I accomplish this in version `0.3.0-alpha.33` of Aleph?

```shell
$ aleph --version
aleph.js 0.3.0-alpha.33
deno 1.10.3
v8 9.1.269.27
typescript 4.2.
```

**Comment by asbjornu** [comment]
This is probably due to me not understanding React well enough, but I finally figured out that I'm able to retrieve the query parameters as such:

```js
import { useRouter } from 'framework/react'
const { query } = useRouter()
const max = query.get('max')
const offset = query.get('offset')
```

This has thus boiled down to a documentation issue around the `import` statement.

**Comment by rumlyne** [comment]
Import maps are documented in both [deno](https://deno.land/manual@v1.11.0/linking_to_external_code/import_maps) and [aleph](https://alephjs.org/docs/basic-features/import-maps)

In your import_map.json you'll likely find the following entry:
` "framework/react": "https://deno.land/x/aleph@v0.3.0-alpha.33/framework/react/mod.ts" `
which can then be imported like you did (preferred):
`import { useRouter } from "framework/react"`
or just using the full path:
`import { useRouter } from "https://deno.land/x/aleph@v0.3.0-alpha.33/framework/react/mod.ts"`

alephs `useRouter()` was moved to mod.ts in the `framework/react` subfolder and other react functions have also been moving around a lot during development. It's easiest to just search them in the github repo and then add a full or partial path to import map.
