### ISSUE TITLE
support tls in dev mode

### ISSUE THREAD

**Issue by codehz** [alephjs/aleph.js#353]
some browser feature are only working in secure context (and localhost, but we may debug it in another device, so we cannot use localhost)

**Comment by guiguan** [comment]
Probably use a caddy proxy https://caddyserver.com/

**Comment by codehz** [comment]
> Probably use a caddy proxy https://caddyserver.com/

yeah, it is a workaround, but since the start command has already support tls, i think it is possible to make dev command support too

**Comment by ije** [comment]
will support this in beta.1 #321

**Comment by ije** [comment]
added in beta.1
