### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by MichailVestnik** [alephjs/aleph.js#355]
Hi! 
1. deno install --unstable -A -f -n aleph https://deno.land/x/aleph@v0.2.28/cli.ts
2. aleph init hello
3. cd hello
4. aleph dev
Result: 
![Снимок экрана от 2021-08-11 12-35-26](https://user-images.githubusercontent.com/87961969/128965931-d75f6e60-38ac-4da7-9ebd-85f65bc49746.png)

**Comment by vincenzopalazzo** [comment]
I suggest to you pull the last version, the version on the site it is a little bit old.
