### ISSUE TITLE
staticPaths

### ISSUE THREAD

**Issue by jb-san** [alephjs/aleph.js#356]
I saw that the option to specify [staticPaths has been removed](https://github.com/alephjs/aleph.js/commit/d82ec0b64fcd1f8c4631b5f6cb67b9f17f3c100c) , whats the plan for this or are you open for suggestions ?

I do think the getStaticPaths function that Nextjs provides is a good solution since if you have a [pageId].tsx page and want to build that X nr of that with different pageId it makes sense to export that function from the same file.

**Comment by ije** [comment]
in https://github.com/alephjs/aleph.js/pull/321 we added a `ssr` options
