### ISSUE TITLE
RFC: getInitialProps/getClientSideProps

### ISSUE THREAD

**Issue by hazae41** [alephjs/aleph.js#364]
IMHO getInitialProps is very useful but complex to re-implement properly and to bundle properly

What I suggest is `getServerSideProps`, which we already have, combined with a new function named `getClientSideProps`.

This function would generate the props client-side, just like getInitialProps, but without being compatible with the server

- First page load:
  `getServerSideProps` is called
- When the user navigates: 
  `getClientSideProps` is called

This way, no request to the server is made each time the user clicks somewhere, especially if the client already has the props in a cache (e.g. swr)

If `getClientSideProps` is NOT defined, then a request is made and `getServerSideProps` is called server-side (current behaviour)

The bundling of those two functions is easier than `getInitialProps`, and their behavior is more understandable and less error-prone

**Comment by hazae41** [comment]
The problem is that `useDeno` is a hook that only accepts one function

**Comment by talentlessguy** [comment]
there's `ssr` now, I don't think `getServerSideProps` makes sense anymore

for example:

```ts
export const ssr: SSROptions = {
  props: async ({ params }) => {
    const res = await fetch(`http://example.com`)

    if (res.status !== 200) {
      console.log(await res.text())
      return {}
    }

    const json = await res.json()

    return json as WalletData
  },
  paths: () => {
    return []
  }
}
```

**Comment by ije** [comment]
what if we allow to access the `Req` in `useDeno` hook?, for example:

```ts
export default function Page() {
  const version = useDeno((req) => {
    return {
       logined: req.headers.get('Auth') === 'XXX'
    }
  }, { revalidate: 0 })

  return (
    <p>Powered by Deno v{version.deno}</p>
  )
}
```

in `ssr` options:

```ts
export const ssr: SSROptions = {
  props: async ({ params }, req) => {
    return {
       $revalidate: 0,
       logined: req.headers.get('Auth') === 'XXX'
    }
  },
  paths: () => {
    return []
  }
}
```

**Comment by talentlessguy** [comment]
@ije second options makes more sense since it already exposes request parameters

**Comment by hazae41** [comment]
The useDeno hook is very clean to use

**Comment by hazae41** [comment]
> @ije second options makes more sense since it already exposes request parameters

We can put params in req

**Comment by ije** [comment]
updated, and rename **`revalidate`** to **`ttl`**, what do you think? @hazae41 @talentlessguy

**Comment by ije** [comment]
added in **beta.18**
