### ISSUE TITLE
Cache more in production mode

### ISSUE THREAD

**Issue by talentlessguy** [alephjs/aleph.js#369]
At the moment there's static caching but it's not set properly, in a way that stuff still gets requested every time.

`Cache-Control` with `aleph start` and Cloudflare is set `to max-age=14400`

IMO, it should be set to `max-age=14400, immutable` in production, for the best performance in prod.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#revalidation_and_reloading

**Comment by ije** [comment]
should consider the updating, vercel set `Cache-Control` to `public, max-age=0, must-revalidate`, then revalidate `Etag` or `Last-Modified`

**Comment by ije** [comment]
and your can change this in `aleph.config.ts`:

```ts
// aleph.config.ts

export default {
  header: { 'Cache-Control': 'max-age=14400' }
}
```

**Comment by ije** [comment]
ref 3c5637d0ef4dc4d8acd95c556ddc5ce946cff06a
