### ISSUE TITLE
missing example with forms events

### ISSUE THREAD

**Issue by elycheikhsmail** [alephjs/aleph.js#377]
the types for event needs somes examples to be more clear in aleleph/examples section

**Comment by tatemz** [comment]
Are you looking for React form examples in general? Or are you, more specifically, looking for how to have a strongly typed form handler? Or something different altogether?

I have had no issues with event handling like the example below:

```tsx
import React, { FC, ChangeEventHandler } from "https://esm.sh/react@17.0.2";

const MyComponent: FC = () => {
  const onInputChange: ChangeEventHandler<HTMLInputElement> = (e) => {
    console.log(e.target)
  };

  return <input type="text" onChange={onInputChange} />
};
```

**Comment by elycheikhsmail** [comment]
> Are you looking for React form examples in general? Or are you, more specifically, looking for how to have a strongly typed form handler? Or something different altogether?
> 
> I have had no issues with event handling like the example below:
> 
> ```tsx
> import React, { FC, ChangeEventHandler } from "https://esm.sh/react@17.0.2";
> 
> const MyComponent: FC = () => {
>   const onInputChange: ChangeEventHandler<HTMLInputElement> = (e) => {
>     console.log(e.target)
>   };
> 
>   return <input type="text" onChange={onInputChange} />
> };
> ```

thank you
