### ISSUE TITLE
how make page protected by bareer token with aleph ?

### ISSUE THREAD

**Issue by elycheikhsmail** [alephjs/aleph.js#385]
in fact I don't see in alephjs doc how to extract headers from incoming request

**Comment by ije** [comment]
@elycheikhsmail you mean in pages?

**Comment by elycheikhsmail** [comment]
> @elycheikhsmail you mean in pages?

yes

**Comment by ije** [comment]
#364 there is a discussion about `getServerSideProps` which currently we doesn't support

**Comment by elycheikhsmail** [comment]
> #364 there is a discussion about `getServerSideProps` which currently we doesn't support

thanks
