### ISSUE TITLE
Fail to import remote CSS on production build

### ISSUE THREAD

**Issue by you-5805** [alephjs/aleph.js#388]
I see similar(?) issues have been posted several times and ended because the beta was expected to fix it, but it seem not to be fixed.

## Versions  
aleph.js 0.3.0-beta.12  
deno 1.13.2  
v8 9.3.345.11  
typescript 4.3.5  

## Steps to reproduce
1. Create aleph project
    ```
    $ aleph init <project-name>
    ```
2. Add import statement on app.tsx
    ```diff
    import React, { ComponentType } from 'react'
    + import "https://esm.sh/tailwindcss/dist/tailwind.min.css";
    ```
3. Build and Serve
    ```
    $ aleph build && aleph start
    ```
4. See Browser Console (I have no errors in the shell on any of the steps above)

![image](https://user-images.githubusercontent.com/56625097/132988147-7f88684f-ae91-4da4-8d94-e59197397adc.png)

this problem occurs regardless of SSR mode.

## Repo
https://github.com/you-5805/tweet_decorator/tree/front/signin-navigation/front
I have additional error `Uncaught TypeError: Cannot destructure property '~' as it is undefined.` on this repo, but I don't know what cause this difference with the steps above.

![image](https://user-images.githubusercontent.com/56625097/132988281-aec20f0a-d742-4c8a-ba77-d4e1b35fb442.png)

**Comment by ije** [comment]
this has be fixed in beta.17, please `aleph upgrade`, i recommmand you use the `windicss` is working in Aleph.js with _tree-shaking_: https://deno.land/x/aleph_plugin_windicss@v0.0.2

**Comment by ije** [comment]
also added an example in here: https://github.com/alephjs/aleph.js/tree/master/examples/remote-css

**Comment by you-5805** [comment]
@ije 
I solved this by using WindiCSS plugin after the framework upgrade.
Thank you for replying and your awesome plugin!
