### ISSUE TITLE
_aleph/index/main.js import throws "invalid hexadecimal escape sequence"

### ISSUE THREAD

**Issue by shapirodaniel** [alephjs/aleph.js#389]
hi aleph! having a bit of trouble sorting out an uncaught syntax error 

setup:

1. initialize app with <code>aleph dev</code>  
2. navigate to localhost:8080  
3. see the following error 

```
Uncaught SyntaxError: Invalid hexadecimal escape sequence     main.js:1
```

in main.js:  

```javascript
// this line throws
import ".\-\deno.land\x\aleph@v0.3.0-beta.12\framework\react\refresh.js";
```

local environment:  
- Microsoft Windows 10 Enterprise Version 10.0.19042 Build 19042
- aleph.js v0.3.0-beta.12
- deno 1.13.2 (release, x86_64-pc-windows-msvc)
- v8 9.3.345.11
- typescript 4.3.5

repository and branch i'm working off of:  
[github.com/shapirodaniel/aleph-deno, branch ffmpeg](https://github.com/shapirodaniel/aleph-deno)

thanks!

**Comment by ije** [comment]
can you please try the **beta.15**? i think it has be fixed
