### ISSUE TITLE
[v0.3.0-beta.12] Getting errors with init command 

### ISSUE THREAD

**Issue by borsemayur2** [alephjs/aleph.js#392]
I'm getting following errors while using `aleph init` command on WSL 

Deno: 1.14.0

![image](https://user-images.githubusercontent.com/47341981/133543490-72918122-a03b-4ea3-92b0-7f4e43d2b566.png)

**Comment by getspooky** [comment]
Duplicated https://github.com/alephjs/aleph.js/issues/391. thanks for reporting this problem.
