### ISSUE TITLE
"window" and "e.target" have type issues

### ISSUE THREAD

**Issue by akaFTS** [alephjs/aleph.js#405]
Two very common use cases in React are reporting type issues on Aleph/Deno. The first one is `window.open`:

```js
  window.open("https://github.com/akaFTS/bcc-data", "_blank");
```
```
Property 'open' does not exist on type 'Window & typeof globalThis'.deno-ts(2339)
```

And the other one is "e.target.value" when handling uncontrolled inputs:

```js
onChange={(e) => setInput(e.target.value)}
```

```
Property 'value' does not exist on type 'EventTarget & HTMLInputElement'.deno-ts(2339)
```

Not sure if those issues are related to Aleph or Deno itself, but I couldn't find any solutions online.

**Comment by ije** [comment]
check this https://deno.land/manual@v1.14.1/typescript/configuration#targeting-deno-and-the-browser

**Comment by akaFTS** [comment]
Wouldn't it make sense to add those flags to the tsconfig file inside Aleph? Stuff like reading input values using `e.target.value` are very common in React, so perhaps Aleph should handle appropriate typing for those.

**Comment by ije** [comment]
i added the config in https://github.com/alephjs/aleph.js/commit/7ec39d8e7a79ec883f80d6c4e1c124617c9ec9bf
