### ISSUE TITLE
Auto-generated app.tsx has explicit any

### ISSUE THREAD

**Issue by akaFTS** [alephjs/aleph.js#406]
The entrypoint generated by `aleph init` contains some `any` props, and `deno-lint` does not like it:

```ts
type AppProps = {
  Page: ComponentType<any>;
  pageProps: any;
};
```

Any plans on changing this?

**Comment by ije** [comment]
updated it to

```ts
type AppProps = {
  Page: ComponentType<any>;
  pageProps: any;
};
```

**Comment by ije** [comment]
updated the `init` template to remove the `any` types
