### ISSUE TITLE
aleph not support react 18 alpha?

### ISSUE THREAD

**Issue by dfang** [alephjs/aleph.js#416]
tried 

```
"react": "https://esm.sh/react@18.0.0-alpha-5fa4d79b0-20211008?dev",
"react-dom": "https://esm.sh/react-dom@18.0.0-alpha-5fa4d79b0-20211008?dev",
```
or 

```
"react": "https://esm.sh/react@alpha",
"react-dom": "https://esm.sh/react-dom@alpha",
```

in import_map.json,

but {React.version} still prints 17.02

**Comment by ije** [comment]
i found the bug here: https://github.com/alephjs/aleph.js/blob/ac6ca05e600f72aa741ee952ab2ce1df663ede18/server/config.ts#L196, will fix it asap thanks
