### ISSUE TITLE
Invalid Hook Call on importing ant components

### ISSUE THREAD

**Issue by akash-joshi** [alephjs/aleph.js#43]
Hey guy ! Been trying aleph since I really like the concept. However, I faced some issues while importing the default ant components. The thing threw the "Invalid Hook Call" error even though I hadn't defined any hooks.

You can check out `pages/index.tsx` in this repo https://github.com/akash-joshi/my-own-writing-app/tree/aleph-dev

Thanks for the help in advanced.

**Comment by shadowtime2000** [comment]
I believe [this line](https://github.com/akash-joshi/my-own-writing-app/blob/aleph-dev/app.tsx#L2) should be a problem because I believe Aleph doesn't support using `import "something.css"` currently.

**Comment by ije** [comment]
@akash-joshi thanks, i will run your example to figure it out what happened.

**Comment by ije** [comment]
@akash-joshi sorry i can not repeat the error, can you post the log messages?

![localhost_8080_(Desktop HD)](https://user-images.githubusercontent.com/2883484/99627811-f54af980-2a6f-11eb-843e-4e3c767e8c38.png)

**Comment by akash-joshi** [comment]
So an update, it did work. I had to clear the aleph cache by running `rm -rf .aleph` to make it work.

Thanks a lot for your help :). I was going to make a video on Deno + React and Aleph is going to play a central role in it.

**Comment by ije** [comment]
cool, maybe the `reload` flag can help you to clean up the build cache next time:
```bash
aleph dev --reload
```
