### ISSUE TITLE
Aleph install instructions leave users with "command not found: aleph"

### ISSUE THREAD

**Issue by JoshuaSchlichting** [alephjs/aleph.js#431]
Installed on macOS Big Sur with zsh, using instructions from https://alephjs.org/docs/get-started

Current Deno version:
```
$ deno --version
deno 1.16.2 (release, x86_64-apple-darwin)
v8 9.7.106.2
typescript 4.4.2
```

Install instructions from https://alephjs.org/docs/get-started as of the timestamp of this post:
> Installation
> you will need Deno 1.13+ to run Aleph.js server.
> `$ deno run -A https://deno.land/x/aleph/install.ts`
> Usage
> Create a new app:
> `$ aleph init`
```
$ deno run -A https://deno.land/x/aleph/install.ts

   [...]

Aleph.js was installed successfully
Run 'aleph -h' to get started
$ aleph -h
zsh: command not found: aleph
$ aleph init
zsh: command not found: aleph
```

**Comment by AnInternetTroll** [comment]
How did you install deno?
And can you run `$DENO_INSTALL/bin/aleph -h`?

**Comment by JoshuaSchlichting** [comment]
Deno was installed via [`brew`](https://brew.sh).

```
$ $DENO_INSTALL/bin/aleph -h
zsh: no such file or directory: /bin/aleph
```

**Comment by JoshuaSchlichting** [comment]
Deno was installed via [`brew`](https://brew.sh).

```
$ $DENO_INSTALL/bin/aleph -h
zsh: no such file or directory: /bin/aleph
```

**Comment by AnInternetTroll** [comment]
After a very quick peak at their [formula](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/deno.rb) they don't install deno with [the proper script](https://deno.land/x/install/install.sh) nor do they set `DENO_INSTALL` and add `DENO_INSTALL/bin` to `PATH` as the script would instruct you to, so in that case `deno install` will never work with anything, not just aleph (which calls `deno install` behind the scenes)

**Comment by JoshuaSchlichting** [comment]
I ran the aleph install commands inside of a [`denoland/deno:1.16.2`](https://hub.docker.com/r/denoland/deno) container and all is working properly. With that, I think your assessment sounds accurate!

@AnInternetTroll, thank you for your assistance this Saturday morning!

**Comment by chezhe** [comment]
You can also add `~/.deno/bin` to `$PATH`

**Comment by stav** [comment]
In my case `~/.deno/bin` was already in my path but `land aleph` did not create the `aleph` script there so I did it and it worked.

    echo 'exec deno run -A "https://deno.land/x/aleph@v0.3.0-beta.19/cli.ts" "$@"' > ~/.deno/bin/aleph
    chmod 755 ~/.deno/bin/aleph
