### ISSUE TITLE
Dev & Production Server Not Working

### ISSUE THREAD

**Issue by shadowtime2000** [alephjs/aleph.js#44]
I created a basic project with `aleph init` and the development server is basically not working. If I go to `localhost:8080` I just get `404 page not found`. This is the same case for the production server. The only thing that is working for me is `aleph build` which seems to be building properly.

**Comment by shadowtime2000** [comment]
[Reproduction repo](https://github.com/shadowtime2000/playing-around-with-aleph).

**Comment by shadowtime2000** [comment]
This is probably a problem with my system and not with Aleph so here is some of my environment information:
OS: Windows 10 10.0.19041
if other pieces of information are necessary I can give them.

**Comment by ije** [comment]
can you please post the terminal log messages?

**Comment by shadowtime2000** [comment]
@ije These are the logs, which I believe are normal.
![image](https://user-images.githubusercontent.com/66655515/99702542-c4a49900-2a4a-11eb-90da-fe149caea483.png)

**Comment by ije** [comment]
please try `v0.2.25`, I'm not sure it is caused by #39 
```bash
deno run -A https://deno.land/x/aleph@v0.2.25/cli.ts dev --reload
```

**Comment by ije** [comment]
yeah, strange...anyway i will try it on windows port, thanks

**Comment by shadowtime2000** [comment]
@ije Have you tried it out?

**Comment by shadowtime2000** [comment]
Nvm, I figured it out. Something else was blocking port 8080 and changing the port made it work.

**Comment by ije** [comment]
@shadowtime2000 do you think we should change the default port **8080** port?

**Comment by shadowtime2000** [comment]
@ije No not really, it was just a problem on my computer.

**Comment by johnwhitefalcon** [comment]
Hello i have the same problem as this and i havent been able to work out how to solve it. Can you let me know how this was fixed. thanks

**Comment by johnwhitefalcon** [comment]
Hi ije can you let me know if you can think of solution to this (i can send screenshot of the google console if that helps) thanks

**Comment by ije** [comment]
@johnwhitefalcon  can you pls post the content from http://localhost:3000/_aleph/main.js

**Comment by johnwhitefalcon** [comment]
Hi ije can you recommend a resource i can use to understand how to do this "@johnwhitefalcon normally, the routes should include the routes info from pages/ dir, ensure the cwd includes the pages dir with index.tsx at less"   thanks

**Comment by johnwhitefalcon** [comment]
Hi ije i have tried a for different directories. initially i had my aleph files inside a folder on my desktop and i have moved them to a folder in my C:\ . Inside VScode i have tried running aleph from inside their folder as well as outside the folder where aleph is saved. I always get the not found 404 error. I have also checked that aleph is installed properly and updated the version of aleph. I just cannot get it to work??

**Comment by johnwhitefalcon** [comment]
Hi ije is there any other way i can solve the not found 404 error with aleph. Will uninstalling aleph and reinstalling it work. What do you think would be the chance that i would get this error if i buy a new computer and install aleph from scratch??   thanks

**Comment by johnwhitefalcon** [comment]
Hi ije did you have a chance to test this on virtualbox to see why i am getting this error   thanks
