### ISSUE TITLE
deploy to vercel "Command deno run -A https://deno.land/x/aleph/cli.ts build exited with 1"

### ISSUE THREAD

**Issue by bobwatcherx** [alephjs/aleph.js#448]
my vercel settings dashboard:

build command : deno run -A https://deno.land/x/aleph/cli.ts build
output : dist
install command : curl -fsSL https://deno.land/x/install/install.sh | DENO_INSTALL=/usr/local sh

but i have error

Error! Command "deno run -A https://deno.land/x/aleph/cli.ts build" exited with 1

**Comment by TomokiMiyauci** [comment]
You maybe need to fix the version of Deno.

Build command: /vercel/.deno/bin/deno run -A https://deno.land/x/aleph/cli.ts build
Installl command: curl -fsSL https://deno.land/x/install/install.sh | sh -s v1.18.0

**Comment by TomokiMiyauci** [comment]
@bobwatcherx

**Comment by bobwatcherx** [comment]
I Will try it .


Pada tanggal Sel, 1 Mar 2022 11.34, Satoshi ***@***.***>
menulis:

**Comment by bobwatcherx** [comment]
> /vercel/.deno/bin/deno run -A https://deno.land/x/aleph/cli.ts build

**SOLVED , THANKS**
