### ISSUE TITLE
Warning: Expected server HTML to contain a matching <div> in <div>.

### ISSUE THREAD

**Issue by tomkimsour** [alephjs/aleph.js#457]
when starting my app with ```land aleph dev```
everything seems to compile just fine but when I open the page in a web browser, I get error 404 and the console shows this message 
```
react-dom.development.js:72 Warning: Expected server HTML to contain a matching <div> in <div>.
    at div
    at Err (http://localhost:8080/-/deno.land/x/aleph@1.0.0-alpha.6/framework/react/router.ts:211:16)
    at Router (http://localhost:8080/-/deno.land/x/aleph@1.0.0-alpha.6/framework/react/router.ts:10:26)
```

**Comment by ije** [comment]
sorry, i did some break changes in alpha.6, you fix it by change `<ssr-body>` to `<!-- ssr-body -->` in the `index.html`

**Comment by ije** [comment]
alpha.8 fixed the 404 error, please try again, thanks!
