### ISSUE TITLE
Necessity of VSCode-specific files

### ISSUE THREAD

**Issue by italodeandra** [alephjs/aleph.js#46]
### Off-topic

Hi guys, first of all congratulations on the library it seems really promising. It actually got me into deno again, I'll be trying it in some hobby projects and maybe in the future contribute for it to get production-ready.

This "issue" is actually a discussion, but as the discussion feature is not available I think it might not be bad submitting an issue, you guys can close and suggest me a better place if I'm wrong.

## Necessity of VSCode-specific files

I would like to understand the necessity of the library adding VSCode-specific files when using the CLI `init` command. This is the first template that I see doing it and think it was really unnecessary but I still would like to understand better the necessity of it.

My suggestion would be either making it an optional flag or using `--template` like CRA.

**Comment by ije** [comment]
hi @italodeandra, thanks for your suggestion, yes you are right i have a plan to provide an *UI* for the `init` command that let people customize them started app in **v0.3**(#5). if you are interested in it welcome to contribute, thanks

**Comment by ije** [comment]
VSCode-specific files is optional now.
please upgrade to **@v0.3.0-alpha.2**.
