### ISSUE TITLE
[framework/vue] Missing route data when redirect page

### ISSUE THREAD

**Issue by ije** [alephjs/aleph.js#467]
@linbingquan can you please have a look? data from SSR is ok.

https://user-images.githubusercontent.com/2883484/167843623-728d7102-ac55-4606-b290-e5ba91799006.mov

**Comment by linbingquan** [comment]
https://github.com/alephjs/aleph.js/blob/c32e2c65e1efc81f53dbdf9d3be4b10bb5e9ae7a/framework/vue/router.ts#L57-L63

I found it is execute twice, it make data is `undefined`.

**Comment by ije** [comment]
thanks 👍
