### ISSUE TITLE
each example must has  it's config

### ISSUE THREAD

**Issue by elycheikhsmail** [alephjs/aleph.js#469]
I try to run vue example in local but don't know how ? what must be the config file content ? what must be import map ? what command ?...if there deno.json file and import_map.json and command in read me it will we be easy to run this example in local.

**Comment by ije** [comment]
when you execute `cli.ts init` all the config will be added, in the framework repo they share the top config

**Comment by elycheikhsmail** [comment]
That means aleph cli init generate react example by default and vue example when --template vue flag passed
