### ISSUE TITLE
UnoCSS example doesn't work

### ISSUE THREAD

**Issue by o-az** [alephjs/aleph.js#487]
Tried opening the UnoCSS example https://aleph-unocss.deno.dev:

![https://aleph-unocss.deno.dev/](https://user-images.githubusercontent.com/23618431/176043132-15dd2e62-b560-4f7b-a4b4-1057a99d517c.png)

**Comment by ije** [comment]
fixed, it's error of the icons-preset fetch icon SVG from CDN
