### ISSUE TITLE
deno vendor 

### ISSUE THREAD

**Issue by xuybin** [alephjs/aleph.js#502]
deno run -A https://deno.land/x/aleph@1.0.0-alpha.90/init.ts --template react

C:\aleph90> deno vendor .\main.tsx .\server.ts 
Vendored 135 modules into vendor/ directory.

C:\aleph90> deno task dev
Warning deno task is unstable and may drastically change in the future
Task dev deno run -A -q server.ts --dev
error: Relative import path "react" not prefixed with / or ./ or ../ and not in import map from "file:///C:/aleph90/vendor/deno.land/x/aleph@1.0.0-alpha.90/runtime/react/context.ts"
    at file:///C:/aleph90/vendor/deno.land/x/aleph@1.0.0-alpha.90/runtime/react/context.ts:2:31

**Comment by ThatBlockyPenguin** [comment]
What did you do to fix this? I'm having the same issue.
