### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by purpledrosophila** [alephjs/aleph.js#51]
Hi everyone!
I'm a technical writer, and I'm contributing to a ghostwritten article about Aleph.js features. I can't tell you where it is because of company NDAs, but rest assured that it's positive and should make more people interested in the framework. Anyway, doing the article really piqued my interest, so I did a deep dive into your docs. I was wondering, since I've been writing software documentation for a long time, and this framework seems interesting -- may I help you out with the documentation? I'm always interested in helping out with some new projects if people are interested. I'm a former software developer myself, so I could do user docs or dev docs, whichever you need most. If you don't need help right now, that's perfectly fine; I could help out anytime.

**Comment by shadowtime2000** [comment]
@purpledrosophila You can contribute to the documentation [here](https://github.com/alephjs/alephjs.org).

**Comment by ije** [comment]
hi @purpledrosophila, you are welcome to imporve our documentation! please follow the docs repo link @shadowtime2000 metioned, thanks!
