### ISSUE TITLE
Set CORS Headers using Middleware

### ISSUE THREAD

**Issue by Abiti-936** [alephjs/aleph.js#512]
I am trying to build a Rest API using Alephjs & Alephjs file based routing is Great, but When I am trying to set CORS headers for all routes, I can't do it using a middleware.

I am try to do it like these:

```ts
import { serve } from "aleph/server";
import routes from "./routes/_export.ts";
import cors from "https://deno.land/x/edge_cors@0.2.1/src/cors.ts";

serve({
  router: { routes },
  middlewares: [
    {
      name: "cors-middleware",
      async fetch(request, { next }) {
        // next() will invoke a respective route function 
        const response = await next();
        return cors(request, response);
      },
    },
  ],
});
```

I think there should be a way of getting a route response within a middleware? 

Thanks.

**Comment by ije** [comment]
in **1.0.0-beta.20** you can do this!
