### ISSUE TITLE
Missing Vue with Twind (Unocss)

### ISSUE THREAD

**Issue by pandasoli** [alephjs/aleph.js#522]
I tried to make a Vue project with Twind using Unocss like the projects gave as examples of this.
But no success. Could you guys make a example of this using Vue pls?

**Comment by ije** [comment]
you need to add `unocss` option, example:

```ts
import { serve } from "aleph/react-server";
import routes from "./routes/_export.ts";

serve({
  baseUrl: import.meta.url,
  router: { routes },
  ssr: true,
  unocss: {
     test: /\.vue$/,
     presets: [ /* your unocss presets here */ ]
  }
});
```

**Comment by pandasoli** [comment]
@ije it didn't work. Well, take a look in the [repo](https://github.com/pandasoli/pandasoli)

This also happens:
![image](https://user-images.githubusercontent.com/76575902/212810074-f4f41eca-5a94-4746-9ecf-84c27bd01f28.png)

**Comment by pandasoli** [comment]
At first it didn't work. So I took the opportunity to clean a little, the template came with a lot stuff that I don't use.
So I committed and executed again to see, and... worked.
I don't know why but it worked.
But the error in the image above keeps
