### ISSUE TITLE
Error: Uncaught (in promise) TypeError: serverEntry.startsWith is not a function

### ISSUE THREAD

**Issue by vikaskaliramna** [alephjs/aleph.js#544]
1. Initialized project 
2. Didn't change anything and used command `deno task dev`
3. Don't know why I get this error.

```cmd
error: Uncaught (in promise) TypeError: serverEntry.startsWith is not a function
    ? serverEntry.startsWith("file://") ? path.fromFileUrl(serverEntry) : path.resolve(serverEntry)
                  ^
    at dev (https://deno.land/x/aleph@1.0.0-beta.36/server/dev.ts:91:19)
    at file:///C:/Users/Administrator/WebstormProjects/project04/dev.ts:3:1

```

* EDIT :  This error does not occur in command `deno task start`.

**Comment by ije** [comment]
which template are you using?

**Comment by maximyurevich** [comment]
> 1. Initialized project
> 2. Didn't change anything and used command `deno task dev`
> 3. Don't know why I get this error.
> 
> ```batchfile
> error: Uncaught (in promise) TypeError: serverEntry.startsWith is not a function
>     ? serverEntry.startsWith("file://") ? path.fromFileUrl(serverEntry) : path.resolve(serverEntry)
>                   ^
>     at dev (https://deno.land/x/aleph@1.0.0-beta.36/server/dev.ts:91:19)
>     at file:///C:/Users/Administrator/WebstormProjects/project04/dev.ts:3:1
> ```
> 
> * EDIT :  This error does not occur in command `deno task start`.

You should update your server.ts, deno.json import_map.json, because some breaking changes :)

**Comment by ije** [comment]
the new `dev` task command is: "deno run -A https://deno.land/x/aleph@1.0.0-beta.37/dev.ts", now you don't need the dev.ts file

**Comment by vikaskaliramna** [comment]
React with Markdown Support.

**Comment by ije** [comment]
> React with Markdown Support.

1.0.0-beta.38 should work fine
