### ISSUE TITLE
Extension issue in browser.

### ISSUE THREAD

**Issue by vikaskaliramna** [alephjs/aleph.js#547]
This doesn't work.
```ts
import { ComponentButton } from '../Library/Component.TS';
```
but this works
```ts
import { ComponentButton } from '../Library/Component.ts';
```

Deno Console shows no error if the extension is uppercase but lots of errors in browser.

Same goes for StyleSheet files.

**Comment by maximyurevich** [comment]
> This doesn't work.
> 
> ```ts
> import { ComponentButton } from '../Library/Component.TS';
> ```
> 
> but this works
> 
> ```ts
> import { ComponentButton } from '../Library/Component.ts';
> ```
> 
> Deno Console shows no error if the extension is uppercase but lots of errors in browser.
> 
> Same goes for StyleSheet files.

Is this wrong behaviour?

**Comment by cdoremus** [comment]
I don';t know if it is a rule, but it is a general convention that extensions (like .ts) are lower case. Most modern programming languages including JavaScript and TypeScript are case-sensitive.

**Comment by vikaskaliramna** [comment]
.TS works in Deno...
