### ISSUE TITLE
SSR TypeError: Cannot read properties of null (reading 'useState')

### ISSUE THREAD

**Issue by omar2205** [alephjs/aleph.js#549]
I'm trying to use `deno task start` but it's failing.

Steps:

1. Run `deno run -A -r https://alephjs.org/init.ts`
2. Choose React, and yes to all
3. Run `deno task start`
4. You get greeted with this
![image](https://user-images.githubusercontent.com/1373867/227791395-84d69969-593c-4e74-8ae5-a8c706ba8e30.png)

**Comment by ije** [comment]
try to execute `deno cache -r https://esm.sh/react@18.2.0`

**Comment by omar2205** [comment]
It fixed the generated template. Now when I try to add this code it breaks again with 
```
Cannot read properties of null (reading 'useState')
```

```ts
import { useEffect, useState } from "react"
// ...

  const [c, setC] = useState(0)

  useEffect(() => {
    const i = setInterval(() => {
      setC(c + 1);
    }, 500)
    return () => clearInterval(i)
  }, [])

```

**Comment by ije** [comment]
please change  `"react": "https://esm.sh/react@18.2.0"` to "react": "https://esm.sh/v113/react@18.2.0" in your import map and `jsxImportSource` in deno.json

**Comment by ije** [comment]
https://github.com/alephjs/aleph.js/commit/ea32ee235b628d21715eb2003156dbad3fa8bfe1 fixed this cache issue

**Comment by omar2205** [comment]
mmm, I update that import but still.
Here is a repo with the problem https://github.com/omar2205/aleph-q-react

**Comment by ije** [comment]
<img width="1009" alt="Screenshot 2023-03-27 at 03 08 31" src="https://user-images.githubusercontent.com/2883484/227798480-f565cfed-3ee4-476e-a3bc-8e835bdfbe98.png">
seems it works for me

**Comment by ije** [comment]
> Cannot read properties of null (reading 'useState')

where you got the message? is devtools console?

**Comment by omar2205** [comment]
Are you running `deno task start`?


![image](https://user-images.githubusercontent.com/1373867/227798689-fd49d926-fb4e-46ad-a450-f2c65ccb3eed.png)

**Comment by omar2205** [comment]
... I had to `CTRL+SHIFT+R` 🤦
