### ISSUE TITLE
Can't remove aleph logo from title

### ISSUE THREAD

**Issue by pita238** [alephjs/aleph.js#58]
Hi,

I removed logo from index.tsx and app.tsx but aleph logo is still present in title of webpage.

**Comment by shadowtime2000** [comment]
It is probably because you have to remove the `favicon.ico` from the `public` folder, because i know Chrome will automatically fetch it unless it is specified in one of the `<head>` tags.

**Comment by ije** [comment]
hi @pita238, like @shadowtime2000 said, you can remove the `favicon.ico` file, but it may still present because browser cache. you can add below `<head>` tags to force refresh the favicon:

```tsx
<head>
  <link rel="alternate icon" type="image/png" href="/favicon.png">
  <link rel="icon" type="image/svg+xml" href="/favicon.svg">
</head>
```

**Comment by pita238** [comment]
Hi, I am using firefox, I deleted favicon.ico from pulic folder earlier but situation is the same.
Now I tried solution rom Mr. ije and it's working, the logo icon from title is gone. Tanks guys.
