### ISSUE TITLE
/About example is not working

### ISSUE THREAD

**Issue by pita238** [alephjs/aleph.js#61]
I tried example for pages/about.tsx but it is not working, when I go to "localhost:8080/about" it redirect me to localhost:8080.
I copied the same code from example at https://alephjs.org/docs/basic-features/pages but nothing, in terminal also there is no errors.
In firefox in transfer column I get NS_BINDING ABORTED. In terminal: modify /pages/about.tsx

**Comment by ije** [comment]
@pita238 are your working in windows? if so, i guess it's path separator issue same with #44. I will fix it ASAP.

**Comment by pita238** [comment]
> 
> 
> @pita238 are your working in windows? if so, i guess it's path separator issue same with #44. I will fix it ASAP.

Yes, windows 10, firefox, visual studio code

**Comment by ije** [comment]
thanks for the information, I will try it on windows later.
btw, are you an architect? i saw the cad/revit haha.

**Comment by pita238** [comment]
> 
> 
> thanks for the information, I will try it on windows later.
> btw, are you an architect? i saw the cad/revit haha.

I am mechanical engineer.

**Comment by ije** [comment]
cool, i ask that because i worked as architectural design in the early years.

**Comment by pita238** [comment]
> 
> 
> cool, i ask that because i worked as an architectural designer in the early years.

Big transition from architectural design to coding, extra. I am working as maintenance engineer in thermal power plant and I am very interesting in coding, I am playing with sql databases, javascript and web programming.

**Comment by ije** [comment]
me too, my favorite languages are typescript, golang, rust. and l like postgres, but hate sql, so i created https://github.com/postui/postdb haha..

**Comment by pita238** [comment]
> 
> 
> me too, my favorite languages are typescript, golang, rust. and l like postgres, but hate sql, so i created https://github.com/postui/postdb haha..

I was working in Node little but then Deno attracted my attention, I am using sql lite with deno for some data extraction and it is ok for me. I am interested in coding because I can relieve my work with my team on the work and also I would like to work online in coding field (as beginer and as second job in the begining). I am quick learner and I am ready if someone needs profile like me.

**Comment by leopku** [comment]
> me too, my favorite languages are typescript, golang, rust. and l like postgres, but hate sql, so i created https://github.com/postui/postdb haha..

It sounds great. I like it.

**Comment by ije** [comment]
pls ref #116
