### ISSUE TITLE
Option to change hostname?

### ISSUE THREAD

**Issue by CoolDeveloper101** [alephjs/aleph.js#66]
Currently, the aleph.js cli only provides the option to change the port number.

![image](https://user-images.githubusercontent.com/49064764/102961925-a5969c80-450b-11eb-84d3-c9cf70ffe22f.png)

However sometimes, a user may also want to change the hostname.

For example - 
`aleph dev --host 0.0.0.0 --port 8080`

Should I implement this feature or this unnecessary?

**Comment by shadowtime2000** [comment]
@CoolDeveloper101 Just asking, why would a user want to change the host name of the development server? I don't know much about backends and servers, but I think this would be possible and it probably would be a good addition to the production `aleph start` command.

**Comment by CoolDeveloper101** [comment]
Yeah you are right. I will soon open a pull request implementing the `--host` flag for the start command.

**Comment by ije** [comment]
@CoolDeveloper101 thanks
