### ISSUE TITLE
Use Rhum for Testing

### ISSUE THREAD

**Issue by shadowtime2000** [alephjs/aleph.js#68]
[Rhum](https://drash.land/rhum/v1.x/#/) is a testing framework built on top of `Deno.test` created by the team behind the [Drash REST API framework](https://drash.land/drash/v1.x/#/). This is only necessary when we have more tests, so I am marking it as future for now. 

Refs:
1. [Documentation site for Rhum](https://drash.land/rhum/v1.x/#/)
2. [v2 issue for Rhum (drashland/rhum#75)](https://github.com/drashland/rhum/issues/75)

**Comment by ije** [comment]
centainly we need full testings! what different `rhum` between `Deno.test`? why we should use it?

**Comment by shadowtime2000** [comment]
@ije `rhum` allows us to more easily organize and compose our tests. Here is part of the example they give on the front page:
```ts
// 1. Define your test plan (usually the test file's name)
// 2. Define your test suites (usually methods being tested)
// 3. Define your test cases with assertions
Rhum.testPlan("app_test.ts", () => {
  Rhum.testSuite("run()", () => {
    Rhum.testCase("Returns true", () => {
      const result = run();
      Rhum.asserts.assertEquals(true, result);
    });
  });
  Rhum.testSuite("close()", () => {
    Rhum.testCase("Returns true", async () => {
      const result = await close();
      Rhum.asserts.assertEquals(true, result);
    });
  });
});
```
idk how much code we have but i think we have like 5k so i think it would be best to organize our tests like that.

**Comment by ije** [comment]
Rhum is cool, but i think `deno.test` is enough, let's keep the testings as simple as possible.
