### ISSUE TITLE
Add Preload Link Tags To Head

### ISSUE THREAD

**Issue by shadowtime2000** [alephjs/aleph.js#7]
Because this project does not bundle the output of a build it is importing from links at runtime. We should probably add `<link rel="preload" />` tags in the header for the static output so the browser knows to start fetching those files.

**Comment by ije** [comment]
that makes sense

**Comment by ije** [comment]
you can check #5 optimize section, this is in the plan

**Comment by shadowtime2000** [comment]
👍 I will take a go at it.

**Comment by shadowtime2000** [comment]
Continuing a conversation from Discord, the preloading of scripts/modules should be improved to preload the actual scripts which are used from the `<script>` tags. The rust compiler #28 could output a dependency graph which could be used for stuff like this. We will also need to change this for production when it will bundle the dependencies.

**Comment by ije** [comment]
preload scripts is done in production mode, no need in dev
