### ISSUE TITLE
Custom 404 error response for apis?

### ISSUE THREAD

**Issue by CoolDeveloper101** [alephjs/aleph.js#70]
Currently the 404 error response for api's has been hardcoded.
![image](https://user-images.githubusercontent.com/49064764/103066352-b401b880-45de-11eb-8e28-3c27e40ecbda.png)
Will it be feasible to allow a custom /api/404.ts for errors or will that be unnecessary?

**Comment by shadowtime2000** [comment]
I don't think it is that necessary but could possibly instead open it up to a custom message in `aleph.config.ts`. @CoolDeveloper101 Do you think that would fit your needs and stuff?

**Comment by CoolDeveloper101** [comment]
@shadowtime2000 
Well now that I thought about it, this is very stupid feature and unnecessary. However can you take a look at [this](https://github.com/alephjs/alephjs-templates/issues/2#issue-774188890) issue I opened? It discusses improving the hello-world template.
