### ISSUE TITLE
Allow https in aleph

### ISSUE THREAD

**Issue by CoolDeveloper101** [alephjs/aleph.js#71]
I saw the the v0.3.0 roadmap and it includes adding SSL/TLS support which is very important for production.
It will probably be not that hard to implement since Deno already has the serveTLS API to create https web servers.
However, instead of crowding the command line with more options, I think the some options like these should be used in the aleph.config.js
```typescript
export default {
	"ssl": true | false // default is false
        "certFile": string // required if ssl == true
        "keyFile": string // required if ssl == true
}
```
Should I try to implement it?

**Comment by shadowtime2000** [comment]
@CoolDeveloper101 Hi, sorry for taking such a long time to respond, I think it would be great if you could implement it yourself. I don't know much about SSL/TLS but don't many hosting providers automatically create certificates or something?

**Comment by CoolDeveloper101** [comment]
Yes, that is true, however we shouldn't probably rely on that. It is not guaranteed that a hosting provider would provide a certificate.

**Comment by shadowtime2000** [comment]
@CoolDeveloper101 Makes sense, I think it would be better to determine if SSL is on or off based on the existence of the related attributes, and then allow forcing it to not be on with `"ssl": true`.
