### ISSUE TITLE
`aleph dev` got `Uncaught (in promise) ReferenceError: Cannot access 'fromFileUrl14' before initialization`

### ISSUE THREAD

**Issue by knightf** [alephjs/aleph.js#74]
MacOS 10.15.7, env:
* aleph.js 0.2.27
* deno 1.6.2
* v8 8.8.278.2
* typescript 4.1.3

When running `aleph dev` after `aleph init`, got this error:
```
error: Uncaught (in promise) ReferenceError: Cannot access 'fromFileUrl14' before initialization
    at https://esm.x-static.io/v12/_node_fs.js:2510:22
```

And by looking into https://esm.x-static.io/v12/_node_fs.js file, variable `fromFileUrl14` does appear before it is declared.

Anyone experiencing the same issue?

**Comment by ije** [comment]
@knightf i just update the ems.sh server, now it should work.

`aleph dev --reload`

**Comment by knightf** [comment]
> @knightf i just updated the ems.sh server, now it should work.
> 
> ```shell
> deno cache --reload https://deno.land/x/aleph@v0.2.27/project.ts
> ```

um... don't know if it is my network enviroment or something else, still got some errors:

```
error: Uncaught (in promise) TypeError: Error: Unable to resolve media type for specifier: "https://esm.x-static.io/v13/typescript@4.1.2/lib/typescript.d.ts"
    at processResponse (deno:core/core.js:223:11)
    at Object.jsonOpSync (deno:core/core.js:246:12)
    at Object.resolveModuleNames (deno:cli/tsc/99_main_compiler.js:303:29)
    at actualResolveModuleNamesWorker (deno:cli/tsc/00_typescript.js:105298:133)
    at resolveModuleNamesWorker (deno:cli/tsc/00_typescript.js:105536:26)
    at resolveModuleNamesReusingOldState (deno:cli/tsc/00_typescript.js:105650:24)
    at processImportedModules (deno:cli/tsc/00_typescript.js:107137:35)
    at findSourceFileWorker (deno:cli/tsc/00_typescript.js:106909:17)
    at findSourceFile (deno:cli/tsc/00_typescript.js:106771:26)
    at deno:cli/tsc/00_typescript.js:106728:85
```

it is either `typescript.d.ts`, or `https://esm.x-static.io/v13/@types/marked@1.2.1/index.d.ts`, or `https://esm.x-static.io/v13/@types/react@17.0.0/index.d.ts` that fails...

**Comment by ije** [comment]
@knightf you can try to remove the total deno cache dir in `deno info` and `_aleph` dir，esm.sh may be vary slow in china  since it is using the CDN of cloudflare, but will download js/dts files from CDN of Aliyun, I will add a standalone server in HK for china mainland in the future.

**Comment by ije** [comment]
this is a esm.sh CDN issue that have be fixed.

**Comment by knightf** [comment]
> this is a esm.sh CDN issue that have be fixed.

https://esm.x-static.io/v13/@types/react@17.0.0/index.d.ts, got this:
```
/* esm.sh - error */
throw new Error("[esm.sh] " + "esbuild: Unexpected \"as\"");
export default null;
```

**Comment by ije** [comment]
pls clean the deno cache:

```bash
deno cache --reload https://esm.sh/react@17.0.0
```
