### ISSUE TITLE
Give an Option for Bundling

### ISSUE THREAD

**Issue by shadowtime2000** [alephjs/aleph.js#8]
Some people (like me) would prefer to have the files bundled together instead of having `import` statements in the final build. It would be great if there was an option to use something like [denopack](https://github.com/denofn/denopack) or `Deno.bundle`.

**Comment by ije** [comment]
can't use *denopack* or *deno.Bundle*, since we need to split code for **pages**, i have a plan to bundle all the deps in `-` directory

**Comment by ije** [comment]
and this will be a part of the new compiler written in rust (i am focusing this currently)
