### ISSUE TITLE
Source map url improperly encoded for dynamic routes

### ISSUE THREAD

**Issue by FallingSnow** [alephjs/aleph.js#88]
When loading a dynamic route, the source map that attempts to be loaded is already url encoded.
![Screenshot from 2021-01-13 16-26-04](https://user-images.githubusercontent.com/2512197/104528442-23eed780-55bc-11eb-9d93-07d41bff2ccc.png)

404 - `http://localhost:8080/_aleph/pages/pipeline/view/%5Bname%5D.js.map`
200 - `http://localhost:8080/_aleph/pages/pipeline/view/[name].js.map`

**Comment by FallingSnow** [comment]
This can be resolved by moving `decodeURI` from
https://github.com/alephjs/aleph.js/blob/0456c9da64ba09967a1b376358c93e8991bdff97/server.ts#L67
to
https://github.com/alephjs/aleph.js/blob/0456c9da64ba09967a1b376358c93e8991bdff97/server.ts#L20

**Comment by ije** [comment]
thanks @FallingSnow , can you please make a PR? or I will fix this in swc branch.

**Comment by FallingSnow** [comment]
Pull: #95
