### ISSUE TITLE
Deno 1.7.0 incompatibility

### ISSUE THREAD

**Issue by FallingSnow** [alephjs/aleph.js#92]
```js
$ aleph dev 
Check https://deno.land/x/aleph@v0.2.28/cli.ts
Check https://deno.land/x/aleph@v0.2.28/cli/dev.ts
error: Uncaught (in promise) NotSupportedError: Cannot set "location".
        throw new DOMException(`Cannot set "location".`, "NotSupportedError");
              ^
    at set (deno:op_crates/web/12_location.js:340:15)
    at Function.assign (<anonymous>)
    at Project._init (project.ts:600:16)
    at async project.ts:106:13
    at async start (server.ts:12:5)

$ deno --version
deno 1.7.0 (release, x86_64-unknown-linux-gnu)
v8 8.9.255.3
typescript 4.1.3

```

See https://github.com/denoland/deno/issues/4981#issuecomment-685205034

**Comment by FallingSnow** [comment]
See for more info.
https://github.com/alephjs/aleph.js/blob/0456c9da64ba09967a1b376358c93e8991bdff97/project.ts#L620

**Comment by FallingSnow** [comment]
Possibly related changes to `globalThis.location`: https://deno.land/posts/v1.7#add-support-for-codeglobalthislocationcode-and-relative-fetch

**Comment by shadowtime2000** [comment]
We have to figure out some way for the SSR part to basically run with `--location`. This will need some more thought.

**Comment by FallingSnow** [comment]
Okie.

I do feel if this doesn't break anything and does solve the issue, this or another fix should be added. Would be a bummer if someone came along with everything up to date and aleph fails.

**Comment by shadowtime2000** [comment]
I don't know for sure but I think the new compiler is changing the way we do SSR

**Comment by ije** [comment]
@FallingSnow  you are right, i think we can use `Object.defineProperty` hack deno's limit.

**Comment by ije** [comment]
ensure we can get a right `location` object in SSR, even i don't recommend to access it.

**Comment by shadowtime2000** [comment]
> @FallingSnow you are right, i think we can use `Object.defineProperty` to hack deno's limit.

It doesn't seem like that is possible

![image](https://user-images.githubusercontent.com/66655515/105280286-46559780-5b5e-11eb-834d-6b08cc7b3d6d.png)

**Comment by ije** [comment]
ok, i'm going to remove all the browser polyfill objects: https://github.com/alephjs/aleph.js/pull/28/commits/068062fb94e9b08fafd6d23e42b35ab9d317b0a3

**Comment by ije** [comment]
i just released an alpha version, now it should work in deno **1.7**:

```bash
deno install -A -f --location=http://localhost -n aleph https://deno.land/x/aleph@v0.3.0-alpha.1/cli.ts
```

**Comment by alundiak** [comment]
Just in case, someone will surf for latest 2021 issue... I got deno `v1.10.1` and aleph `v0.3.0-alpha.33` and initial installation was as:

```
deno install --unstable -A -f -n aleph https://deno.land/x/aleph@v0.3.0-alpha.33/cli.ts
```

And then executing `aleph dev` I got:

```
ERROR invoke API: ReferenceError: Access to "location", run again with --location <href>.
    at get (deno:extensions/web/12_location.js:365:17)
    at createStorage (deno:extensions/webstorage/01_webstorage.js:91:28)
    at localStorage (deno:extensions/webstorage/01_webstorage.js:178:24)
    at handler (file:///...MY../.aleph/development/api/counter/index.js#9786cc:2:28)
    at Server.handle (https://deno.land/x/aleph@v0.3.0-alpha.33/server/server.ts:189:21)
```

Note: localhost:8080 worked/running well.

I got some reading [here](https://deno.com/blog/v1.7#add-support-for-globalthis.location-and-relative-fetch) and this issue last comment got me a hint, so I re-installed aleph:

```
deno install -A -f --location=http://localhost -n aleph https://deno.land/x/aleph@v0.3.0-alpha.33/cli.ts
```
And now `aleph dev` is "clean".

Not yet sure, if `--unstable` matters here.

**Comment by shadowtime2000** [comment]
@alundiak That is already a problem that has been reported, though an issue has not been made. Could you create one so it could be tracked somewhere else?

**Comment by alundiak** [comment]
@shadowtime2000 I wanted to avoid duplication, I've already seen a few similar issues and PRs. So I will not create a new one. Unless it will appear again with deno `1.11.x` for example in future.

**Comment by shadowtime2000** [comment]
@alundiak I mean like, commenting on a dead issue that was resolved months ago doesn't really help avoid duplication lol. but okay.

**Comment by ije** [comment]
the old aleph `upgrade` command didn't add the `location` flag, i will improve the upgrade command for bootstrap options changes, you can use the `deno run -A https://deno.land/x/aleph/install.ts`
