### ISSUE TITLE
Better CSS Imports

### ISSUE THREAD

**Issue by shadowtime2000** [alephjs/aleph.js#97]
According to the documentation, currently we just transform CSS files into [JS files which append the CSS to the `<head>`](https://alephjs.org/docs/basic-features/built-in-css-support#how-it-works). This isn't that performant, I think we should look into possibly concatenating the CSS and writing it to a folder.

**Comment by FallingSnow** [comment]
Is appending CSS to the head less performant than downloading an addition CSS file?

**Comment by shadowtime2000** [comment]
@FallingSnow Oh, it actually isn't, but we are kind of resetting the styles on hydration when it is unnecessary so I think that is something to look at.

**Comment by FallingSnow** [comment]
Would it solve the issue if styles were loaded before content? In that case I don't think you would get any visible style changes during hydration.

**Comment by shadowtime2000** [comment]
What I am talking about is the [`applyCSS` implementation](https://github.com/alephjs/aleph.js/blob/659337e33846250e1f0e8e6c4977838caff0e549/framework/react/style.ts#L55). If it is running server side [it will set the styles for SSR](https://github.com/alephjs/aleph.js/blob/659337e33846250e1f0e8e6c4977838caff0e549/framework/react/style.ts#L57) but if not, [it will append a style element to the head which is unnecessary as it is already setting the styles for SSR](https://github.com/alephjs/aleph.js/blob/659337e33846250e1f0e8e6c4977838caff0e549/framework/react/style.ts#L58).

**Comment by ije** [comment]
@shadowtime2000  you are right, this should be improved (first `applyCSS` should be ignored)! but we better to write css to js since we need to load page component/styling dynamically, even in production(bundling) mode.

**Comment by ije** [comment]
we need the `applyCSS` for HMR and page routing.
